"""The committed flight geopotential table must still match its `.gfc` source.

`lib/gnc/egm2008_low_degree.hpp` is a *derived* artifact: generated by
``tools/gravity/cxxtable.py`` from the committed ICGEM ``.gfc``
(``tests/golden/EGM2008_to200.gfc``), which is the reference datum per design doc
§3.7. Committing the derivation as well as the source is what lets flight code
carry the field without file I/O — and it is also how the two silently drift
apart, so this regenerates and compares on every run, the same discipline the
GMAT golden fixtures get (§23.1).

The comparison is on the parsed **coefficients**, not on bytes. clang-format owns
the committed file's whitespace and the generator does not, so a byte comparison
would fail the first time the formatter reflowed a row without a single number
having changed.
"""

from __future__ import annotations

import math
import re
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "tools"))

from gravity.cxxtable import (  # noqa: E402
    MAX_SAFE_DEGREE,
    denormalization_factor,
    emit_header,
    parse_coefficients,
    parse_header,
)

GFC = REPO_ROOT / "tests" / "golden" / "EGM2008_to200.gfc"
HEADER = REPO_ROOT / "lib" / "gnc" / "egm2008_low_degree.hpp"


def _parse_cxx_table(text: str, name: str, max_degree: int) -> list[list[float]]:
    """Pull the ``kC`` or ``kS`` table out of the generated header.

    Deliberately parses the committed file rather than trusting the generator to
    describe itself: the point of the test is to read what is actually compiled
    into flight.
    """
    start = text.index(f"double {name}[kMaxDegree + 1][kMaxDegree + 1] = {{")
    end = text.index("};", start)
    body = text[start:end]
    rows = re.findall(r"\{([^{}]*)\}", body)
    if len(rows) != max_degree + 1:
        raise AssertionError(
            f"{name}: expected {max_degree + 1} rows, found {len(rows)}"
        )
    return [
        [float(v) for v in row.replace("\n", " ").split(",") if v.strip()]
        for row in rows
    ]


@pytest.fixture(scope="module")
def committed() -> str:
    if not HEADER.exists():
        pytest.fail(f"generated header missing: {HEADER}")
    return HEADER.read_text()


@pytest.fixture(scope="module")
def source() -> str:
    if not GFC.exists():
        pytest.skip(f"committed .gfc not present: {GFC}")
    return GFC.read_text()


def _max_degree(text: str) -> int:
    return int(re.search(r"kMaxDegree = (\d+);", text).group(1))


def test_committed_header_matches_a_fresh_generation(
    committed: str, source: str
) -> None:
    """Every coefficient in the committed header is what the `.gfc` says it is."""
    max_degree = _max_degree(committed)
    expected = parse_coefficients(source, max_degree)

    for name, index in (("kC", 0), ("kS", 1)):
        table = _parse_cxx_table(committed, name, max_degree)
        for n in range(max_degree + 1):
            for m in range(max_degree + 1):
                want = expected.get((n, m), (0.0, 0.0))[index] if m <= n else 0.0
                got = table[n][m]
                assert got == want, (
                    f"{name}[{n}][{m}] is {got!r} in the committed header but {want!r} when "
                    f"regenerated from {GFC.name} — regenerate with "
                    f"`PYTHONPATH=tools uv run python -m gravity cxx-header --input "
                    f"{GFC.relative_to(REPO_ROOT)} --max-degree {max_degree} --out "
                    f"{HEADER.relative_to(REPO_ROOT)}`"
                )


def test_committed_header_carries_the_models_own_constants(
    committed: str, source: str
) -> None:
    """`kGm` / `kReferenceRadius` come from the `.gfc` header, not from WGS84.

    The coefficients were solved with these; pairing them with a generic constant
    reintroduces an error comparable to the truncation the table exists to
    remove, which is why ``OrbitOdConfig::isValid`` cross-checks them.
    """
    head = parse_header(source)
    gm = float(re.search(r"kGm = ([-\de.+]+);", committed).group(1))
    radius = float(re.search(r"kReferenceRadius = ([-\de.+]+);", committed).group(1))
    assert gm == head["gm"]
    assert radius == head["radius"]


def test_regeneration_is_deterministic(source: str) -> None:
    """Two generations of the same input agree byte for byte.

    Not a tautology: `repr` of a float, dict iteration order and the greedy line
    wrapper are all places a generator can become order-dependent, and a
    non-deterministic one would make the drift test above flap instead of fail.
    """
    a = emit_header(source, 8, str(GFC))
    b = emit_header(source, 8, str(GFC))
    assert a == b


def test_denormalization_matches_the_closed_form() -> None:
    """N_nm against the factorial expression, independent of `lgamma`.

    ``denormalization_factor`` works in log space to stay finite at high degree.
    At low degree the direct factorial form is exact and available, so the two
    are compared where both are valid — which is what catches a transposed
    ``(n-m)!``/``(n+m)!`` that log space would hide as a sign flip.
    """
    for n in range(0, 9):
        for m in range(0, n + 1):
            delta = 1.0 if m == 0 else 0.0
            direct = math.sqrt(
                (2.0 - delta)
                * (2 * n + 1)
                * math.factorial(n - m)
                / math.factorial(n + m)
            )
            assert denormalization_factor(n, m) == pytest.approx(direct, rel=1e-13)


def test_generator_refuses_a_degree_the_recursion_cannot_carry(source: str) -> None:
    """Above `MAX_SAFE_DEGREE` the unnormalized coefficients stop being usable.

    The flight evaluator uses the unnormalized Cunningham V/W recursion, whose
    sectoral terms grow like ``(2n-1)!!``. Refusing here is what stops a future
    "just bump the degree" from producing a table that silently loses precision.
    """
    with pytest.raises(ValueError):
        emit_header(source, MAX_SAFE_DEGREE + 1, str(GFC))
    with pytest.raises(ValueError):
        emit_header(source, 1, str(GFC))
