"""Regenerate the FreeFlyer SGP4/TLE golden fixture (REQ-ODP-003, REQ-VV-006).

FreeFlyer's SGP4 is the **US Space Force AstroStds library v9.5** — an
implementation lineage independent of the Vallado formulation Polaris runs — and
it reports in ICRF while SGP4 works in TEME, so a comparison against it
exercises ``frames::eciFromTeme`` as well as the propagator.

The case list is deliberately shared with ``tools/gmat/tle.py``: same NORAD
numbers, same sample schedules, drawn from the same committed AIAA verification
set. That is what lets ``sgp4_external_golden_test.cpp`` difference the two
external tools against *each other* as well as against Polaris — a three-way
check where an agreement between any two is meaningful because none of the three
shares code with another.

Run (needs a licensed FreeFlyer install)::

    uv run --group analysis python -m freeflyer sgp4-fixture

CI never runs FreeFlyer; the committed fixture is what every PR compares against.
"""

from __future__ import annotations

import datetime as _dt
import json
from pathlib import Path

from freeflyer import locate, vv

_REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_PATH = _REPO_ROOT / "tests" / "golden" / "freeflyer_sgp4.json"
VERIFICATION_TLE = _REPO_ROOT / "tests" / "golden" / "SGP4-VER.TLE"

#: The five regimes GMAT also runs, plus ``deep_space_decaying`` — the AIAA
#: synthetic case GMAT's SPICE propagator refuses (see ``gmat.tle``'s
#: ``GMAT_UNSUPPORTED``). Keeping it here rather than dropping it everywhere is
#: the point: it stays covered by two independent implementations even though
#: the third declines it.
SGP4_CASES = (
    (
        "leo_near_earth",
        "00005",
        "LEO, e=0.186 — the reference set's first case",
        (0.0, 600.0, 1800.0, 3600.0, 5400.0),
    ),
    (
        "leo_sso",
        "28057",
        "sun-synchronous LEO, near-circular",
        (0.0, 600.0, 1800.0, 3600.0, 5400.0),
    ),
    (
        "molniya_12h_resonant",
        "22674",
        "Molniya, e=0.754 — the 2:1 deep-space resonance",
        (0.0, 3600.0, 10800.0, 21600.0, 43200.0),
    ),
    (
        "geo_24h_synchronous",
        "26900",
        "GEO — the 1:1 deep-space resonance",
        (0.0, 3600.0, 21600.0, 43200.0, 86400.0),
    ),
    (
        "deep_space_non_resonant",
        "04632",
        "deep space, 19.96 h period, e=0.145 — periodics without an active resonance",
        (0.0, 3600.0, 10800.0, 21600.0, 43200.0),
    ),
    (
        "deep_space_decaying",
        "11801",
        "deep space, e=0.732, 151 km perigee, B*=0.143 — GMAT/SPICE refuses this one",
        (0.0, 3600.0, 10800.0, 21600.0, 43200.0),
    ),
)


def load_fixture_tle(norad: str, path: Path = VERIFICATION_TLE) -> tuple[str, str]:
    """The two lines for *norad*, truncated to the 69 columns of the format.

    The committed fixture appends the reference driver's start/stop/step to line
    2; that is not part of a TLE and no external parser need tolerate it.
    """
    lines = [
        line.rstrip("\n")
        for line in path.read_text(encoding="ascii").splitlines()
        if not line.startswith("#")
    ]
    for i in range(len(lines) - 1):
        if lines[i].startswith(f"1 {norad}"):
            return lines[i][:69], lines[i + 1][:69]
    raise ValueError(f"NORAD {norad} not found in {path}")


def regenerate() -> dict:
    """Run every case through FreeFlyer and return the fixture dict."""
    install = locate.find_runnable_licensed()
    if install is None:
        raise RuntimeError(
            "no runnable licensed FreeFlyer install found — this regenerates a "
            "committed fixture and cannot be faked"
        )
    cases = []
    for name, norad, note, times in SGP4_CASES:
        line1, line2 = load_fixture_tle(norad)
        samples = vv.run_tle_case(install, name, line1, line2, list(times))
        cases.append(
            {
                "name": name,
                "norad": norad,
                "note": note,
                "tle_line1": line1,
                "tle_line2": line2,
                "samples": samples,
            }
        )
    return {
        "_comment": (
            "FreeFlyer SGP4/TLE cross-validation fixture (REQ-ODP-003, REQ-VV-006). "
            "Generated by tools/freeflyer/sgp4_fixture.py; CI never runs FreeFlyer. "
            "FreeFlyer's SGP4 is the US Space Force AstroStds library v9.5 -- an "
            "implementation lineage independent of both Polaris (Vallado) and GMAT "
            "(NAIF SPICE) -- and the states are ICRF, so comparing against them "
            "exercises the TEME->ECI conversion as well as the propagator. The case "
            "list matches tests/golden/gmat_sgp4.json except deep_space_decaying, "
            "which GMAT's SPICE propagator refuses."
        ),
        "freeflyer_version": install.license_info.get("version", "7.10.1"),
        "frame": "ICRF",
        "generated_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(
            timespec="seconds"
        ),
        "cases": cases,
    }


def main() -> int:
    fixture = regenerate()
    FIXTURE_PATH.write_text(json.dumps(fixture, indent=2) + "\n")
    for case in fixture["cases"]:
        print(
            f"  {case['name']:26s} NORAD {case['norad']}  {len(case['samples'])} samples"
        )
    print(f"wrote {FIXTURE_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
