"""GMAT golden-data harness for the time-scale fixtures (design doc §23.1).

GMAT is the V&V reference tool (REQ-SYS-010): it generates the versioned golden
datasets that Polaris numerical functions are checked against. This module is the
*regenerate* path — it is NOT run in CI (which only compares against the committed
`tests/golden/*.json`); it runs occasionally, where GMAT is installed, to refresh
the fixtures.

Two pieces, split so the parser is testable without GMAT:

- ``write_time_scales_script`` emits a GMAT ``.script`` that reports each UTC
  epoch in the TAI / UTC / TT systems to a ``ReportFile``.
- ``parse_report`` + ``offsets_from_rows`` turn GMAT's ``ReportFile`` output into
  the scale offsets (TAI−UTC, TT−TAI) that populate the fixture.

Run (with GMAT on PATH)::

    GmatConsole tools/gmat/scripts/time_scales.script   # writes the report
    # then feed the report to build_time_scales_fixture(...) -> tests/golden/time_scales.json

TAI−GPS is the definitional 19 s (GMAT does not emit a GPS system), so it is
carried as a constant, not parsed.
"""

from __future__ import annotations

import math
import subprocess
from pathlib import Path

# GMAT reports Modified Julian dates in days; 1 day = 86400 SI seconds in a
# uniform scale, which is what the TAI/TT/UTC ModJulian columns are.
SECONDS_PER_DAY = 86400.0
TAI_MINUS_GPS_S = 19.0  # definitional (IS-GPS-200); not emitted by GMAT

# A ModJulian epoch near 44244 stored as a float64 has ~1 ULP ≈ 1e-11 day ≈
# 0.85 µs of resolution, and differencing two same-day values inherits it. So a
# scale offset recovered from GMAT MJD columns is trustworthy only to ~1 µs — the
# fixture tolerance a regenerated fixture declares must not claim more.
# ponytail: MJD-float floor; split integer/fractional days if sub-µs is ever needed.
_UTC_KEYS = ("year", "month", "day", "hour", "minute", "second", "nanosecond")
GMAT_MJD_TOL_S = 1.0e-6


def write_time_scales_script(epochs_utc: list[str], report_path: str) -> str:
    """Return a GMAT script that reports TAI/UTC/TT ModJulian for each UTC epoch.

    @p epochs_utc are UTCGregorian strings GMAT understands, e.g.
    ``'06 Jan 1980 00:00:00.000'``. @p report_path is where GMAT writes the report.
    """
    for value in (report_path, *epochs_utc):
        if "'" in value:
            raise ValueError(
                f"single quote would break the GMAT script literal: {value!r}"
            )
    lines = [
        "% Auto-generated by tools/gmat/golden.py — time-scale golden data.",
        "% Regenerates tests/golden/time_scales.json (REQ-VV-002).",
        "Create Spacecraft sat;",
        "sat.DateFormat = UTCGregorian;",
        f"Create ReportFile rf; rf.Filename = '{report_path}';",
        "rf.WriteHeaders = true;",
        "BeginMissionSequence;",
    ]
    for epoch in epochs_utc:
        lines.append(f"sat.Epoch = '{epoch}';")
        lines.append("Report rf sat.TAIModJulian sat.UTCModJulian sat.TTModJulian;")
    return "\n".join(lines) + "\n"


def parse_report(text: str) -> list[dict[str, float]]:
    """Parse a GMAT ``ReportFile``: a header row of column names then numeric rows.

    Returns one dict per data row, keyed by the (bare) column name. Column names
    like ``sat.TAIModJulian`` are reduced to ``TAIModJulian``.
    """
    lines = [ln for ln in text.splitlines() if ln.strip()]
    if not lines:
        raise ValueError("empty GMAT report")
    header = [col.split(".")[-1] for col in lines[0].split()]
    if len(set(header)) != len(header):
        raise ValueError(f"GMAT report has duplicate columns after reduction: {header}")
    rows: list[dict[str, float]] = []
    for ln in lines[1:]:
        values = ln.split()
        if len(values) != len(header):
            raise ValueError(
                f"GMAT report row has {len(values)} cols, header has {len(header)}: {ln!r}"
            )
        parsed = {name: float(v) for name, v in zip(header, values)}
        for name, value in parsed.items():
            if not math.isfinite(value):
                raise ValueError(f"GMAT report has non-finite {name}={value!r}: {ln!r}")
        rows.append(parsed)
    return rows


def offsets_from_rows(rows: list[dict[str, float]]) -> list[dict[str, float]]:
    """Convert TAI/UTC/TT ModJulian rows into scale offsets in seconds."""
    out = []
    for r in rows:
        try:
            tai, utc, tt = r["TAIModJulian"], r["UTCModJulian"], r["TTModJulian"]
        except KeyError as exc:
            raise ValueError(f"GMAT report row missing column {exc}") from exc
        out.append(
            {
                "tai_minus_utc_s": (tai - utc) * SECONDS_PER_DAY,
                "tt_minus_tai_s": (tt - tai) * SECONDS_PER_DAY,
                "tai_minus_gps_s": TAI_MINUS_GPS_S,
            }
        )
    return out


def build_time_scales_fixture(
    case_names: list[str],
    utc_fields: list[dict],
    rows: list[dict[str, float]],
    tol_abs: float = GMAT_MJD_TOL_S,
) -> dict:
    """Assemble the fixture dict from parsed GMAT rows (schema matches the C++ loader).

    ``tol_abs`` defaults to the ~1 µs GMAT-MJD precision floor (``GMAT_MJD_TOL_S``),
    not a tighter value the differenced ModJulian columns cannot actually support.
    """
    offsets = offsets_from_rows(rows)
    if not (len(case_names) == len(utc_fields) == len(offsets)):
        raise ValueError("case_names, utc_fields, and rows must have equal length")
    for utc in utc_fields:
        missing = [k for k in _UTC_KEYS if k not in utc]
        if missing:
            raise ValueError(f"utc case missing required keys {missing}: {utc}")
    cases = []
    for name, utc, off in zip(case_names, utc_fields, offsets):
        cases.append(
            {
                "name": name,
                "utc": utc,
                "quantities": {
                    q: {"expected": round(v, 12), "tol_abs": tol_abs, "unit": "s"}
                    for q, v in off.items()
                },
            }
        )
    return {
        "schema_version": "1.0",
        "case": "time_scales",
        "category": "time_conversion",
        "provenance": {"reference": "GMAT", "gmat_regeneratable": True},
        "cases": cases,
    }


# Canonical epochs the time-scale fixture covers — the single source of truth the
# regenerate and drift-check paths share, so a GMAT run reproduces exactly the two
# committed cases. Each carries the UTCGregorian string GMAT reads plus the
# UtcDateTime fields the C++ loader expects.
TIME_SCALES_CASES = (
    {
        "name": "gps_epoch_1980",
        "epoch_utc": "06 Jan 1980 00:00:00.000",
        "utc": {
            "year": 1980,
            "month": 1,
            "day": 6,
            "hour": 0,
            "minute": 0,
            "second": 0,
            "nanosecond": 0,
        },
    },
    {
        "name": "post_2017_epoch_2020",
        "epoch_utc": "01 Jan 2020 00:00:00.000",
        "utc": {
            "year": 2020,
            "month": 1,
            "day": 1,
            "hour": 0,
            "minute": 0,
            "second": 0,
            "nanosecond": 0,
        },
    },
)


def regenerate_time_scales_fixture(
    gmat_console: str,
    workdir: str,
    cases: tuple[dict, ...] = TIME_SCALES_CASES,
    timeout_s: float = 300.0,
) -> dict:
    """Run GMAT (``gmat_console``) to regenerate the time-scale fixture dict.

    Emits the script for @p cases into @p workdir, runs ``GmatConsole`` on it, then
    parses the report into the fixture. Requires the GMAT binary — callers must gate
    on its presence. Raises ``RuntimeError`` if GMAT produces no report.
    """
    work = Path(workdir)
    report_path = work / "time_scales_report.txt"
    script_path = work / "time_scales.script"
    script_path.write_text(
        write_time_scales_script([c["epoch_utc"] for c in cases], str(report_path))
    )
    # ponytail: some GMAT builds resolve gmat_startup_file.txt relative to their own
    # bin/ — if a bare invocation can't find it, point gmat_console at a wrapper that
    # cd's into GMAT's bin first, or pass an absolute console path.
    result = subprocess.run(  # noqa: S603 — console path is operator-supplied, not user input
        [gmat_console, str(script_path)],
        capture_output=True,
        text=True,
        timeout=timeout_s,
        check=False,
    )
    if not report_path.exists():
        raise RuntimeError(
            f"GMAT produced no report at {report_path} (exit={result.returncode}).\n"
            f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )
    rows = parse_report(report_path.read_text())
    return build_time_scales_fixture(
        case_names=[c["name"] for c in cases],
        utc_fields=[c["utc"] for c in cases],
        rows=rows,
    )


def compare_time_scales(committed: dict, regenerated: dict) -> list[str]:
    """Return drift messages; empty means GMAT agrees with the committed fixture.

    Each committed quantity must match the GMAT-regenerated value within the looser
    of the two tolerance bands — GMAT's ~µs ModJulian floor dominates the committed
    fixture's tighter 1 ns claim, so the check is honest about GMAT's own precision.
    """

    def index(fixture: dict) -> dict:
        return {
            (case["name"], qname): spec
            for case in fixture["cases"]
            for qname, spec in case["quantities"].items()
        }

    want, got = index(committed), index(regenerated)
    messages: list[str] = []
    for key, spec in want.items():
        if key not in got:
            messages.append(f"{key}: missing from GMAT regeneration")
            continue
        tol = max(spec["tol_abs"], got[key]["tol_abs"])
        diff = abs(spec["expected"] - got[key]["expected"])
        if diff > tol:
            messages.append(
                f"{key}: committed {spec['expected']} vs GMAT {got[key]['expected']} "
                f"(|Δ|={diff:.3e} > tol {tol:.1e})"
            )
    return messages
