"""GMAT golden-data harness for the time-scale fixtures (design doc §23.1).

GMAT is the V&V reference tool (REQ-SYS-010): it generates the versioned golden
datasets that Polaris numerical functions are checked against. This module is the
*regenerate* path — it is NOT run in CI (which only compares against the committed
`tests/golden/*.json`); it runs occasionally, where GMAT is installed, to refresh
the fixtures.

Two pieces, split so the parser is testable without GMAT:

- ``write_time_scales_script`` emits a GMAT ``.script`` that reports each UTC
  epoch in the TAI / UTC / TT systems to a ``ReportFile``.
- ``parse_report`` + ``offsets_from_rows`` turn GMAT's ``ReportFile`` output into
  the scale offsets (TAI−UTC, TT−TAI) that populate the fixture.

Run (with GMAT on PATH)::

    GmatConsole tools/gmat/scripts/time_scales.script   # writes the report
    # then feed the report to build_time_scales_fixture(...) -> tests/golden/time_scales.json

TAI−GPS is the definitional 19 s (GMAT does not emit a GPS system), so it is
carried as a constant, not parsed.
"""

from __future__ import annotations

import math

# GMAT reports Modified Julian dates in days; 1 day = 86400 SI seconds in a
# uniform scale, which is what the TAI/TT/UTC ModJulian columns are.
SECONDS_PER_DAY = 86400.0
TAI_MINUS_GPS_S = 19.0  # definitional (IS-GPS-200); not emitted by GMAT

# A ModJulian epoch near 44244 stored as a float64 has ~1 ULP ≈ 1e-11 day ≈
# 0.85 µs of resolution, and differencing two same-day values inherits it. So a
# scale offset recovered from GMAT MJD columns is trustworthy only to ~1 µs — the
# fixture tolerance a regenerated fixture declares must not claim more.
# ponytail: MJD-float floor; split integer/fractional days if sub-µs is ever needed.
_UTC_KEYS = ("year", "month", "day", "hour", "minute", "second", "nanosecond")
GMAT_MJD_TOL_S = 1.0e-6


def write_time_scales_script(epochs_utc: list[str], report_path: str) -> str:
    """Return a GMAT script that reports TAI/UTC/TT ModJulian for each UTC epoch.

    @p epochs_utc are UTCGregorian strings GMAT understands, e.g.
    ``'06 Jan 1980 00:00:00.000'``. @p report_path is where GMAT writes the report.
    """
    for value in (report_path, *epochs_utc):
        if "'" in value:
            raise ValueError(
                f"single quote would break the GMAT script literal: {value!r}"
            )
    lines = [
        "% Auto-generated by tools/gmat/golden.py — time-scale golden data.",
        "% Regenerates tests/golden/time_scales.json (REQ-VV-002).",
        "Create Spacecraft sat;",
        "sat.DateFormat = UTCGregorian;",
        f"Create ReportFile rf; rf.Filename = '{report_path}';",
        "rf.WriteHeaders = true;",
        "BeginMissionSequence;",
    ]
    for epoch in epochs_utc:
        lines.append(f"sat.Epoch = '{epoch}';")
        lines.append("Report rf sat.TAIModJulian sat.UTCModJulian sat.TTModJulian;")
    return "\n".join(lines) + "\n"


def parse_report(text: str) -> list[dict[str, float]]:
    """Parse a GMAT ``ReportFile``: a header row of column names then numeric rows.

    Returns one dict per data row, keyed by the (bare) column name. Column names
    like ``sat.TAIModJulian`` are reduced to ``TAIModJulian``.
    """
    lines = [ln for ln in text.splitlines() if ln.strip()]
    if not lines:
        raise ValueError("empty GMAT report")
    header = [col.split(".")[-1] for col in lines[0].split()]
    if len(set(header)) != len(header):
        raise ValueError(f"GMAT report has duplicate columns after reduction: {header}")
    rows: list[dict[str, float]] = []
    for ln in lines[1:]:
        values = ln.split()
        if len(values) != len(header):
            raise ValueError(
                f"GMAT report row has {len(values)} cols, header has {len(header)}: {ln!r}"
            )
        parsed = {name: float(v) for name, v in zip(header, values)}
        for name, value in parsed.items():
            if not math.isfinite(value):
                raise ValueError(f"GMAT report has non-finite {name}={value!r}: {ln!r}")
        rows.append(parsed)
    return rows


def offsets_from_rows(rows: list[dict[str, float]]) -> list[dict[str, float]]:
    """Convert TAI/UTC/TT ModJulian rows into scale offsets in seconds."""
    out = []
    for r in rows:
        try:
            tai, utc, tt = r["TAIModJulian"], r["UTCModJulian"], r["TTModJulian"]
        except KeyError as exc:
            raise ValueError(f"GMAT report row missing column {exc}") from exc
        out.append(
            {
                "tai_minus_utc_s": (tai - utc) * SECONDS_PER_DAY,
                "tt_minus_tai_s": (tt - tai) * SECONDS_PER_DAY,
                "tai_minus_gps_s": TAI_MINUS_GPS_S,
            }
        )
    return out


def build_time_scales_fixture(
    case_names: list[str],
    utc_fields: list[dict],
    rows: list[dict[str, float]],
    tol_abs: float = GMAT_MJD_TOL_S,
) -> dict:
    """Assemble the fixture dict from parsed GMAT rows (schema matches the C++ loader).

    ``tol_abs`` defaults to the ~1 µs GMAT-MJD precision floor (``GMAT_MJD_TOL_S``),
    not a tighter value the differenced ModJulian columns cannot actually support.
    """
    offsets = offsets_from_rows(rows)
    if not (len(case_names) == len(utc_fields) == len(offsets)):
        raise ValueError("case_names, utc_fields, and rows must have equal length")
    for utc in utc_fields:
        missing = [k for k in _UTC_KEYS if k not in utc]
        if missing:
            raise ValueError(f"utc case missing required keys {missing}: {utc}")
    cases = []
    for name, utc, off in zip(case_names, utc_fields, offsets):
        cases.append(
            {
                "name": name,
                "utc": utc,
                "quantities": {
                    q: {"expected": round(v, 12), "tol_abs": tol_abs, "unit": "s"}
                    for q, v in off.items()
                },
            }
        )
    return {
        "schema_version": "1.0",
        "case": "time_scales",
        "category": "time_conversion",
        "provenance": {"reference": "GMAT", "gmat_regeneratable": True},
        "cases": cases,
    }
