"""GMAT golden-data harness for the orbit-propagation fixtures (design doc §23.1).

Companion to :mod:`gmat.golden` (time scales): this module cross-validates the
Polaris orbit propagator against GMAT's RungeKutta89 integrator over three force
models — two-body, zonal J2, and third-body Sun/Moon — and emits
``tests/golden/gmat_propagation.json`` for the C++ golden test to replay.

Same split as the time-scale harness, so everything except the GMAT run itself is
unit-testable without the binary:

- ``write_propagation_script`` emits the ``.script`` for one case.
- ``samples_from_rows`` turns GMAT's ``ReportFile`` rows (km, km/s) into SI
  samples, and ``build_propagation_fixture`` assembles the fixture dict.
- ``compare_propagation`` is the drift function, mirroring ``compare_time_scales``.

GMAT's ``Propagate ... {sat.ElapsedSecs = N}`` stop condition overshoots N by a
few hundred ns. The fixture records GMAT's *actual* reported ElapsedSecs, never
the nominal grid value, so the C++ side propagates to exactly the sampled times
and the overshoot cancels rather than showing up as position error.
"""

from __future__ import annotations

import subprocess
from datetime import date
from pathlib import Path

from .golden import parse_report

KM_TO_M = 1000.0

# Reported state columns, in the order the generated Report command emits them.
_STATE_COLUMNS = ("X", "Y", "Z", "VX", "VY", "VZ")

# Every case flies the same 6U-class spacecraft; point-mass gravity, drag off and
# SRP off make the propagation mass-independent, so these only pin down what the
# C++ side must construct, not the trajectory.
SPACECRAFT = {
    "mass_kg": 12.0,
    "inertia_kgm2": {"ixx": 0.12, "iyy": 0.12, "izz": 0.10},
}

EPOCH_UTC_GREGORIAN = "01 Jan 2026 00:00:00.000"
EPOCH_UTC_ISO = "2026-01-01T00:00:00Z"


def write_propagation_script(case: dict, report_path: str) -> str:
    """Return a GMAT script propagating @p case and reporting its state history.

    @p case is one entry of ``PROPAGATION_CASES``: it supplies the force-model
    lines, the initial Cartesian state in km / km s^-1, and the sampling grid.
    @p report_path must be absolute — GMAT resolves relative paths against its own
    ``bin/`` directory.
    """
    for value in (report_path, case["name"]):
        if "'" in value:
            raise ValueError(
                f"single quote would break the GMAT script literal: {value!r}"
            )
    pos_km, vel_km_s = case["position_km"], case["velocity_km_s"]
    # GMAT rejects non-ASCII bytes in a script, so every emitted line stays ASCII.
    lines = [
        f"% Auto-generated by tools/gmat/propagation.py - case '{case['name']}'.",
        "% Regenerates tests/golden/gmat_propagation.json (REQ-VV-002).",
        # Match wgs84::kGM = 3.986004418e14 exactly, so the two-body comparison is
        # not dominated by a gravitational-parameter mismatch.
        "Earth.Mu = 398600.4418;",
        *case.get("preamble_lines", ()),
        "Create Spacecraft sat;",
        "sat.DateFormat = UTCGregorian;",
        f"sat.Epoch = '{EPOCH_UTC_GREGORIAN}';",
        "sat.CoordinateSystem = EarthMJ2000Eq;",
        f"sat.X = {pos_km[0]!r};",
        f"sat.Y = {pos_km[1]!r};",
        f"sat.Z = {pos_km[2]!r};",
        f"sat.VX = {vel_km_s[0]!r};",
        f"sat.VY = {vel_km_s[1]!r};",
        f"sat.VZ = {vel_km_s[2]!r};",
        "Create ForceModel fm;",
        "fm.CentralBody = Earth;",
        *case["force_model_lines"],
        "fm.Drag = None;",
        "fm.SRP = Off;",
        "Create Propagator prop;",
        "prop.FM = fm;",
        "prop.Type = RungeKutta89;",
        "prop.InitialStepSize = 10;",
        "prop.Accuracy = 1e-13;",
        "prop.MinStep = 0;",
        f"prop.MaxStep = {case['sample_step_s']};",
        "Create ReportFile rf;",
        f"rf.Filename = '{report_path}';",
        "rf.WriteHeaders = true;",
        # 16 significant digits: the default 10 would quantise position to ~1 m and
        # swamp the millimetre-level agreement the fixture is meant to record.
        "rf.Precision = 16;",
        "BeginMissionSequence;",
    ]
    report = "Report rf sat.ElapsedSecs " + " ".join(
        f"sat.EarthMJ2000Eq.{col}" for col in _STATE_COLUMNS
    )
    lines.append(f"{report};")
    lines.append(f"While sat.ElapsedSecs < {case['duration_s']}")
    lines.append(
        f"   Propagate prop(sat) {{sat.ElapsedSecs = {case['sample_step_s']}}};"
    )
    lines.append(f"   {report};")
    lines.append("EndWhile;")
    return "\n".join(lines) + "\n"


def samples_from_rows(rows: list[dict[str, float]]) -> list[dict]:
    """Convert GMAT state rows (km, km s^-1) into SI fixture samples.

    ``t_s`` is GMAT's reported ``ElapsedSecs`` verbatim, including its stop-condition
    overshoot — the C++ side propagates to exactly these times.
    """
    samples = []
    for r in rows:
        missing = [c for c in ("ElapsedSecs", *_STATE_COLUMNS) if c not in r]
        if missing:
            raise ValueError(f"GMAT report row missing columns {missing}: {r}")
        samples.append(
            {
                "t_s": r["ElapsedSecs"],
                "position_m": [r[c] * KM_TO_M for c in ("X", "Y", "Z")],
                "velocity_m_s": [r[c] * KM_TO_M for c in ("VX", "VY", "VZ")],
            }
        )
    if not samples:
        raise ValueError("GMAT report contained no state rows")
    if samples[0]["t_s"] != 0.0:
        raise ValueError(f"first sample is t={samples[0]['t_s']}, expected the epoch")
    return samples


def build_propagation_fixture(
    cases: tuple[dict, ...],
    samples_by_case: dict[str, list[dict]],
    generated_utc: str | None = None,
) -> dict:
    """Assemble the fixture dict from per-case samples (schema matches the C++ loader)."""
    missing = [c["name"] for c in cases if c["name"] not in samples_by_case]
    if missing:
        raise ValueError(f"no samples for cases {missing}")
    return {
        "schema_version": "1.0",
        "case": "gmat_propagation",
        "category": "force_model",
        "description": (
            "GMAT RungeKutta89 orbit-propagation reference states for three force "
            "models (two-body, zonal J2, third-body Sun/Moon), cross-validating the "
            "Polaris propagator and force composite."
        ),
        "provenance": {
            "gmat_version": "R2026a",
            "gmat_console": "GmatConsole-R2026a",
            "generated_utc": generated_utc or date.today().isoformat(),
            "gmat_regeneratable": True,
            "scripts": "tools/gmat/scripts/",
            "note": (
                "t_s values are GMAT's reported ElapsedSecs, which overshoot the "
                "nominal sampling grid by ~0.4 us; propagate to these exact times. "
                "States are EarthMJ2000Eq, converted from GMAT's km/km-s to SI."
            ),
        },
        "cases": [
            {
                "name": case["name"],
                "description": case["description"],
                "epoch_utc": EPOCH_UTC_ISO,
                "gmat_script": f"tools/gmat/scripts/prop_{case['name']}.script",
                "environment": case["environment"],
                "spacecraft": SPACECRAFT,
                "initial_state": {
                    "position_m": [v * KM_TO_M for v in case["position_km"]],
                    "velocity_m_s": [v * KM_TO_M for v in case["velocity_km_s"]],
                    "attitude_quaternion": [1.0, 0.0, 0.0, 0.0],
                    "body_rate_rad_s": [0.0, 0.0, 0.0],
                },
                "position_tolerance_m": case["position_tolerance_m"],
                "velocity_tolerance_m_s": case["velocity_tolerance_m_s"],
                "tolerance_rationale": case["tolerance_rationale"],
                "samples": samples_by_case[case["name"]],
            }
            for case in cases
        ],
    }


# Circular 500 km orbits at the J2000-equatorial epoch: equatorial for two-body,
# and a 28 deg-inclined variant reused by the J2 and third-body cases (an inclined
# orbit makes J2 and the lunar/solar pull show up in all three components).
_R_KM = 6878.137
_V_CIRC_KM_S = 7.612608173223869
_V_INCLINED_KM_S = (0.0, 6.721534061926209, 3.573903055960055)

PROPAGATION_CASES = (
    {
        "name": "two_body",
        "description": "Circular 500 km equatorial orbit, Earth point mass only, 1.5 orbits.",
        "position_km": (_R_KM, 0.0, 0.0),
        "velocity_km_s": (0.0, _V_CIRC_KM_S, 0.0),
        "force_model_lines": ("fm.PointMasses = {Earth};",),
        "duration_s": 5400,
        "sample_step_s": 600,
        "environment": {
            "gravity_degree": 0,
            "gravity_order": -1,
            "third_bodies": [],
            "drag_enabled": False,
            "srp_enabled": False,
            "magnetic_field": "none",
        },
        "position_tolerance_m": 0.05,
        "velocity_tolerance_m_s": 1.0e-4,
        "tolerance_rationale": (
            "Pure two-body with Earth.Mu set to wgs84::kGM exactly, so nothing but "
            "integrator truncation separates the two propagators; hand-verified "
            "agreement is 3.8 mm over 1.5 orbits, and the 5 cm band leaves room for "
            "step-control differences."
        ),
    },
    {
        "name": "zonal_j2",
        "description": (
            "Circular 500 km orbit at 28 deg inclination, degree-2 order-0 zonal "
            "gravity (J2 only), 1.5 orbits."
        ),
        "position_km": (_R_KM, 0.0, 0.0),
        "velocity_km_s": _V_INCLINED_KM_S,
        "force_model_lines": (
            "fm.PrimaryBodies = {Earth};",
            "fm.GravityField.Earth.Degree = 2;",
            "fm.GravityField.Earth.Order = 0;",
            "fm.GravityField.Earth.PotentialFile = 'EGM96.cof';",
        ),
        "duration_s": 5400,
        "sample_step_s": 600,
        "environment": {
            "gravity_degree": 2,
            "gravity_order": 0,
            "third_bodies": [],
            "drag_enabled": False,
            "srp_enabled": False,
            "magnetic_field": "none",
        },
        "position_tolerance_m": 0.5,
        "velocity_tolerance_m_s": 1.0e-3,
        "tolerance_rationale": (
            "GMAT uses EGM96 and Polaris uses EGM2008; their normalized C20 values "
            "differ slightly, and that model difference - not propagator error - "
            "dominates the hand-verified 4.7 cm separation over 1.5 orbits. The 0.5 m "
            "band is an order of margin on top of it."
        ),
    },
    {
        "name": "third_body",
        "description": (
            "Circular 500 km orbit at 28 deg inclination, Earth point mass plus Sun "
            "and Moon third-body perturbations, ~4 orbits."
        ),
        "position_km": (_R_KM, 0.0, 0.0),
        "velocity_km_s": _V_INCLINED_KM_S,
        "preamble_lines": ("SolarSystem.EphemerisSource = 'DE424';",),
        "force_model_lines": ("fm.PointMasses = {Earth, Sun, Luna};",),
        "duration_s": 24000,
        "sample_step_s": 600,
        "environment": {
            "gravity_degree": 0,
            "gravity_order": -1,
            "third_bodies": ["sun", "moon"],
            "drag_enabled": False,
            "srp_enabled": False,
            "magnetic_field": "none",
        },
        "position_tolerance_m": 2.0,
        "velocity_tolerance_m_s": 5.0e-3,
        "tolerance_rationale": (
            "GMAT reads DE424 (the closest DE it ships to the DE440 Chebyshev fit "
            "Polaris uses) and any residual is that ephemeris difference, not Polaris "
            "error. Measured directly in GMAT, switching DE405 -> DE424 moves the "
            "4-orbit state by 1.9 cm, so the DE424 -> DE440 residual is expected at "
            "the same centimetre scale; the 2 m band covers it with wide margin plus "
            "the integrator drift accumulated over the longer 4-orbit arc."
        ),
    },
)


def regenerate_propagation_fixture(
    gmat_console: str,
    workdir: str,
    cases: tuple[dict, ...] = PROPAGATION_CASES,
    timeout_s: float = 600.0,
    script_dir: str | None = None,
) -> dict:
    """Run GMAT once per case to regenerate the propagation fixture dict.

    Emits each case's script into @p workdir (or @p script_dir, when the generated
    scripts should also be committed), runs ``GmatConsole`` on it, and parses the
    reports into the fixture. Requires the GMAT binary — callers must gate on its
    presence. Raises ``RuntimeError`` if GMAT produces no report for a case.
    """
    work = Path(workdir)
    samples_by_case: dict[str, list[dict]] = {}
    for case in cases:
        report_path = work / f"prop_{case['name']}_report.txt"
        script_path = work / f"prop_{case['name']}.script"
        script = write_propagation_script(case, str(report_path.resolve()))
        script_path.write_text(script)
        if script_dir is not None:
            (Path(script_dir) / f"prop_{case['name']}.script").write_text(script)
        report_path.unlink(missing_ok=True)
        # GMAT resolves gmat_startup_file.txt and ../data/... relative to its own
        # bin/, so it must run from there; script/report paths are absolute.
        result = subprocess.run(  # noqa: S603 — console path is operator-supplied, not user input
            [gmat_console, "--run", str(script_path.resolve())],
            cwd=str(Path(gmat_console).resolve().parent),
            capture_output=True,
            text=True,
            timeout=timeout_s,
            check=False,
        )
        if not report_path.exists():
            raise RuntimeError(
                f"GMAT produced no report at {report_path} (exit={result.returncode}).\n"
                f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
            )
        samples_by_case[case["name"]] = samples_from_rows(
            parse_report(report_path.read_text())
        )
    return build_propagation_fixture(cases, samples_by_case)


def compare_propagation(committed: dict, regenerated: dict) -> list[str]:
    """Return drift messages; empty means GMAT agrees with the committed fixture.

    Each committed sample must be reproduced by GMAT at the same elapsed time and
    within the case's declared position/velocity tolerance bands.
    """

    def index(fixture: dict) -> dict:
        return {case["name"]: case for case in fixture["cases"]}

    want, got = index(committed), index(regenerated)
    messages: list[str] = []
    for name, case in want.items():
        if name not in got:
            messages.append(f"{name}: missing from GMAT regeneration")
            continue
        fresh = got[name]["samples"]
        if len(fresh) != len(case["samples"]):
            messages.append(
                f"{name}: GMAT returned {len(fresh)} samples, committed has "
                f"{len(case['samples'])}"
            )
            continue
        for old, new in zip(case["samples"], fresh):
            # The stop-condition overshoot is ~0.4 us and reproducible; a shifted
            # sample time means the grid changed, which invalidates the comparison.
            if abs(old["t_s"] - new["t_s"]) > 1.0e-3:
                messages.append(
                    f"{name} t={old['t_s']}: GMAT sampled t={new['t_s']} instead"
                )
                continue
            for field, tol_key in (
                ("position_m", "position_tolerance_m"),
                ("velocity_m_s", "velocity_tolerance_m_s"),
            ):
                diff = max(abs(a - b) for a, b in zip(old[field], new[field]))
                tol = case[tol_key]
                if diff > tol:
                    messages.append(
                        f"{name} t={old['t_s']} {field}: committed {old[field]} vs "
                        f"GMAT {new[field]} (max|Δ|={diff:.3e} > tol {tol:.1e})"
                    )
    return messages
