"""GMAT golden-data harness for the orbit-propagation fixtures (design doc §23.1).

Companion to :mod:`gmat.golden` (time scales): this module cross-validates the
Polaris orbit propagator against GMAT's RungeKutta89 integrator over three force
models — two-body, zonal J2, and third-body Sun/Moon — and emits
``tests/golden/gmat_propagation.json`` for the C++ golden test to replay.

Same split as the time-scale harness, so everything except the GMAT run itself is
unit-testable without the binary:

- ``write_propagation_script`` emits the ``.script`` for one case.
- ``samples_from_rows`` turns GMAT's ``ReportFile`` rows (km, km/s) into SI
  samples, and ``build_propagation_fixture`` assembles the fixture dict.
- ``compare_propagation`` is the drift function, mirroring ``compare_time_scales``.

GMAT's ``Propagate ... {sat.ElapsedSecs = N}`` stop condition overshoots N by a
few hundred ns. The fixture records GMAT's *actual* reported ElapsedSecs, never
the nominal grid value, so the C++ side propagates to exactly the sampled times
and the overshoot cancels rather than showing up as position error.
"""

from __future__ import annotations

import subprocess
from datetime import date
from pathlib import Path

from .golden import parse_report

KM_TO_M = 1000.0

# Reported state columns, in the order the generated Report command emits them.
_STATE_COLUMNS = ("X", "Y", "Z", "VX", "VY", "VZ")

# Every case flies the same 6U-class spacecraft; point-mass gravity, drag off and
# SRP off make the propagation mass-independent, so these only pin down what the
# C++ side must construct, not the trajectory.
SPACECRAFT = {
    "mass_kg": 12.0,
    "inertia_kgm2": {"ixx": 0.12, "iyy": 0.12, "izz": 0.10},
}

EPOCH_UTC_GREGORIAN = "01 Jan 2026 00:00:00.000"
EPOCH_UTC_ISO = "2026-01-01T00:00:00Z"


def write_propagation_script(case: dict, report_path: str) -> str:
    """Return a GMAT script propagating @p case and reporting its state history.

    @p case is one entry of ``PROPAGATION_CASES``: it supplies the force-model
    lines, the initial Cartesian state in km / km s^-1, and the sampling grid.
    @p report_path must be absolute — GMAT resolves relative paths against its own
    ``bin/`` directory.
    """
    for value in (report_path, case["name"]):
        if "'" in value:
            raise ValueError(
                f"single quote would break the GMAT script literal: {value!r}"
            )
    pos_km, vel_km_s = case["position_km"], case["velocity_km_s"]
    # GMAT rejects non-ASCII bytes in a script, so every emitted line stays ASCII.
    lines = [
        f"% Auto-generated by tools/gmat/propagation.py - case '{case['name']}'.",
        "% Regenerates tests/golden/gmat_propagation.json (REQ-VV-002).",
        # Match wgs84::kGM = 3.986004418e14 exactly, so the two-body comparison is
        # not dominated by a gravitational-parameter mismatch.
        "Earth.Mu = 398600.4418;",
        *case.get("preamble_lines", ()),
        "Create Spacecraft sat;",
        "sat.DateFormat = UTCGregorian;",
        f"sat.Epoch = '{EPOCH_UTC_GREGORIAN}';",
        "sat.CoordinateSystem = EarthMJ2000Eq;",
        f"sat.X = {pos_km[0]!r};",
        f"sat.Y = {pos_km[1]!r};",
        f"sat.Z = {pos_km[2]!r};",
        f"sat.VX = {vel_km_s[0]!r};",
        f"sat.VY = {vel_km_s[1]!r};",
        f"sat.VZ = {vel_km_s[2]!r};",
        *case.get("spacecraft_lines", ()),
        *case.get("attitude_lines", ()),
        "Create ForceModel fm;",
        "fm.CentralBody = Earth;",
        *case["force_model_lines"],
        "fm.Drag = None;",
        *case.get("srp_lines", ("fm.SRP = Off;",)),
        "Create Propagator prop;",
        "prop.FM = fm;",
        "prop.Type = RungeKutta89;",
        "prop.InitialStepSize = 10;",
        "prop.Accuracy = 1e-13;",
        "prop.MinStep = 0;",
        f"prop.MaxStep = {case['sample_step_s']};",
        "Create ReportFile rf;",
        f"rf.Filename = '{report_path}';",
        "rf.WriteHeaders = true;",
        # 16 significant digits: the default 10 would quantise position to ~1 m and
        # swamp the millimetre-level agreement the fixture is meant to record.
        "rf.Precision = 16;",
        "BeginMissionSequence;",
    ]
    report = "Report rf sat.ElapsedSecs " + " ".join(
        f"sat.EarthMJ2000Eq.{col}" for col in _STATE_COLUMNS
    )
    extra = case.get("extra_report_params", ())
    if extra:
        report += " " + " ".join(extra)
    lines.append(f"{report};")
    lines.append(f"While sat.ElapsedSecs < {case['duration_s']}")
    lines.append(
        f"   Propagate prop(sat) {{sat.ElapsedSecs = {case['sample_step_s']}}};"
    )
    lines.append(f"   {report};")
    lines.append("EndWhile;")
    return "\n".join(lines) + "\n"


def samples_from_rows(rows: list[dict[str, float]]) -> list[dict]:
    """Convert GMAT state rows (km, km s^-1) into SI fixture samples.

    ``t_s`` is GMAT's reported ``ElapsedSecs`` verbatim, including its stop-condition
    overshoot — the C++ side propagates to exactly these times.
    """
    samples = []
    for r in rows:
        missing = [c for c in ("ElapsedSecs", *_STATE_COLUMNS) if c not in r]
        if missing:
            raise ValueError(f"GMAT report row missing columns {missing}: {r}")
        sample = {
            "t_s": r["ElapsedSecs"],
            "position_m": [r[c] * KM_TO_M for c in ("X", "Y", "Z")],
            "velocity_m_s": [r[c] * KM_TO_M for c in ("VX", "VY", "VZ")],
        }
        if "Q4" in r:
            # GMAT reports the inertial-to-body quaternion scalar-LAST (Q1..Q3
            # vector, Q4 scalar); Polaris is JPL scalar-first [q0, q1, q2, q3].
            sample["attitude_quaternion"] = [r["Q4"], r["Q1"], r["Q2"], r["Q3"]]
        samples.append(sample)
    if not samples:
        raise ValueError("GMAT report contained no state rows")
    if samples[0]["t_s"] != 0.0:
        raise ValueError(f"first sample is t={samples[0]['t_s']}, expected the epoch")
    return samples


def build_propagation_fixture(
    cases: tuple[dict, ...],
    samples_by_case: dict[str, list[dict]],
    generated_utc: str | None = None,
) -> dict:
    """Assemble the fixture dict from per-case samples (schema matches the C++ loader)."""
    missing = [c["name"] for c in cases if c["name"] not in samples_by_case]
    if missing:
        raise ValueError(f"no samples for cases {missing}")
    return {
        "schema_version": "1.0",
        "case": "gmat_propagation",
        "category": "force_model",
        "description": (
            "GMAT RungeKutta89 reference states cross-validating the Polaris "
            "propagator, force composite, and attitude kinematics. Force-model "
            "cases (two_body, zonal_j2, third_body) and an orbit-regime matrix "
            "(iss_leo, sso_leo, geo, molniya_heo) exercise the propagator from LEO "
            "through GEO through a high-eccentricity HEO; attitude_spinner checks "
            "the quaternion attitude propagation against GMAT's Spinner."
        ),
        "provenance": {
            "gmat_version": "R2026a",
            "gmat_console": "GmatConsole-R2026a",
            "generated_utc": generated_utc or date.today().isoformat(),
            "gmat_regeneratable": True,
            "scripts": "tools/gmat/scripts/",
            "note": (
                "t_s values are GMAT's reported ElapsedSecs, which overshoot the "
                "nominal sampling grid by ~0.4 us; propagate to these exact times. "
                "States are EarthMJ2000Eq, converted from GMAT's km/km-s to SI."
            ),
        },
        "cases": [
            {
                "name": case["name"],
                "description": case["description"],
                "epoch_utc": EPOCH_UTC_ISO,
                "gmat_script": f"tools/gmat/scripts/prop_{case['name']}.script",
                "environment": case["environment"],
                # The SRP ballistic properties ride along whenever the case
                # flies SRP: the Polaris side constructs its force from these
                # very fields, and a fixture that omits them is how the GEO
                # case flew for a year with srp_area_m2 defaulting to zero —
                # SRP silently off, 120 m of "model difference" that was
                # actually a disabled force (falsified by FreeFlyer ablation,
                # Push 57).
                "spacecraft": {**SPACECRAFT, **case.get("spacecraft_srp", {})},
                "initial_state": {
                    "position_m": [v * KM_TO_M for v in case["position_km"]],
                    "velocity_m_s": [v * KM_TO_M for v in case["velocity_km_s"]],
                    "attitude_quaternion": [1.0, 0.0, 0.0, 0.0],
                    "body_rate_rad_s": case.get("attitude", {}).get(
                        "body_rate_rad_s", [0.0, 0.0, 0.0]
                    ),
                },
                "position_tolerance_m": case["position_tolerance_m"],
                "velocity_tolerance_m_s": case["velocity_tolerance_m_s"],
                "tolerance_rationale": case["tolerance_rationale"],
                # Present only for attitude cases; the C++ side keys the attitude
                # comparison off its existence.
                **(
                    {
                        "attitude": case["attitude"],
                        "attitude_tolerance_deg": case["attitude_tolerance_deg"],
                    }
                    if "attitude" in case
                    else {}
                ),
                "samples": samples_by_case[case["name"]],
            }
            for case in cases
        ],
    }


# Circular 500 km orbits at the J2000-equatorial epoch: equatorial for two-body,
# and a 28 deg-inclined variant reused by the J2 and third-body cases (an inclined
# orbit makes J2 and the lunar/solar pull show up in all three components).
_R_KM = 6878.137
_V_CIRC_KM_S = 7.612608173223869
_V_INCLINED_KM_S = (0.0, 6.721534061926209, 3.573903055960055)

# Shared degree-8 J2-class environment for the LEO regime cases.
_J2CLASS_ENV = {
    "gravity_degree": 8,
    "gravity_order": 8,
    "third_bodies": [],
    "drag_enabled": False,
    "srp_enabled": False,
    "magnetic_field": "none",
}

PROPAGATION_CASES = (
    {
        "name": "two_body",
        "description": "Circular 500 km equatorial orbit, Earth point mass only, 1.5 orbits.",
        "position_km": (_R_KM, 0.0, 0.0),
        "velocity_km_s": (0.0, _V_CIRC_KM_S, 0.0),
        "force_model_lines": ("fm.PointMasses = {Earth};",),
        "duration_s": 5400,
        "sample_step_s": 600,
        "environment": {
            "gravity_degree": 0,
            "gravity_order": -1,
            "third_bodies": [],
            "drag_enabled": False,
            "srp_enabled": False,
            "magnetic_field": "none",
        },
        "position_tolerance_m": 0.05,
        "velocity_tolerance_m_s": 1.0e-4,
        "tolerance_rationale": (
            "Pure two-body with Earth.Mu set to wgs84::kGM exactly, so nothing but "
            "integrator truncation separates the two propagators; hand-verified "
            "agreement is 3.8 mm over 1.5 orbits, and the 5 cm band leaves room for "
            "step-control differences."
        ),
    },
    {
        "name": "zonal_j2",
        "description": (
            "Circular 500 km orbit at 28 deg inclination, degree-2 order-0 zonal "
            "gravity (J2 only), 1.5 orbits."
        ),
        "position_km": (_R_KM, 0.0, 0.0),
        "velocity_km_s": _V_INCLINED_KM_S,
        "force_model_lines": (
            "fm.PrimaryBodies = {Earth};",
            "fm.GravityField.Earth.Degree = 2;",
            "fm.GravityField.Earth.Order = 0;",
            "fm.GravityField.Earth.PotentialFile = 'EGM96.cof';",
        ),
        "duration_s": 5400,
        "sample_step_s": 600,
        "environment": {
            "gravity_degree": 2,
            "gravity_order": 0,
            "third_bodies": [],
            "drag_enabled": False,
            "srp_enabled": False,
            "magnetic_field": "none",
        },
        "position_tolerance_m": 0.5,
        "velocity_tolerance_m_s": 1.0e-3,
        "tolerance_rationale": (
            "GMAT uses EGM96 and Polaris uses EGM2008; their normalized C20 values "
            "differ slightly, and that model difference - not propagator error - "
            "dominates the hand-verified 4.7 cm separation over 1.5 orbits. The 0.5 m "
            "band is an order of margin on top of it."
        ),
    },
    {
        "name": "third_body",
        "description": (
            "Circular 500 km orbit at 28 deg inclination, Earth point mass plus Sun "
            "and Moon third-body perturbations, ~4 orbits."
        ),
        "position_km": (_R_KM, 0.0, 0.0),
        "velocity_km_s": _V_INCLINED_KM_S,
        "preamble_lines": ("SolarSystem.EphemerisSource = 'DE424';",),
        "force_model_lines": ("fm.PointMasses = {Earth, Sun, Luna};",),
        "duration_s": 24000,
        "sample_step_s": 600,
        "environment": {
            "gravity_degree": 0,
            "gravity_order": -1,
            "third_bodies": ["sun", "moon"],
            "drag_enabled": False,
            "srp_enabled": False,
            "magnetic_field": "none",
        },
        "position_tolerance_m": 0.1,
        "velocity_tolerance_m_s": 1.0e-4,
        "tolerance_rationale": (
            "GMAT reads DE424 (the closest DE it ships to the DE440 Chebyshev fit "
            "Polaris uses) and any residual is that ephemeris difference, not Polaris "
            "error. Measured GMAT-vs-Polaris separation over the 4-orbit arc is "
            "3.9 mm; the 0.1 m band is ~25x margin on an ephemeris-model difference."
        ),
    },
    # --- Orbit-regime matrix: same J2 force model, very different geometries, so
    # the propagator is exercised across the eccentricity/altitude/period range a
    # mission set actually spans (LEO drag-class through GEO through a Molniya HEO).
    {
        "name": "iss_leo",
        "description": "ISS-like 417 km circular orbit at 51.6 deg, degree-8 gravity, ~5 orbits.",
        "position_km": (6795.137, 0.0, 0.0),
        "velocity_km_s": (0.0, 4.7573457613, 6.0022765366),
        "force_model_lines": (
            "fm.PrimaryBodies = {Earth};",
            "fm.GravityField.Earth.Degree = 8;",
            "fm.GravityField.Earth.Order = 8;",
            "fm.GravityField.Earth.PotentialFile = 'EGM96.cof';",
        ),
        "duration_s": 28000,
        "sample_step_s": 700,
        "environment": dict(_J2CLASS_ENV),
        "position_tolerance_m": 2.0,
        "velocity_tolerance_m_s": 5.0e-3,
        "tolerance_rationale": (
            "Degree-8 gravity, EGM96 (GMAT) vs EGM2008 (Polaris): the higher-degree "
            "coefficient differences accumulate over five 51.6 deg orbits. The band "
            "is model difference, not propagator error — the 2 m allowance is a few x "
            "the EGM96/EGM2008 separation at degree 8."
        ),
    },
    {
        "name": "sso_leo",
        "description": (
            "Sun-synchronous 700 km circular orbit at 98.2 deg, degree-8 gravity, "
            "~4 orbits — the mission template regime, retrograde and near-polar."
        ),
        "position_km": (7078.137, 0.0, 0.0),
        "velocity_km_s": (0.0, -1.0703283803, 7.4275643981),
        "force_model_lines": (
            "fm.PrimaryBodies = {Earth};",
            "fm.GravityField.Earth.Degree = 8;",
            "fm.GravityField.Earth.Order = 8;",
            "fm.GravityField.Earth.PotentialFile = 'EGM96.cof';",
        ),
        "duration_s": 24000,
        "sample_step_s": 600,
        "environment": dict(_J2CLASS_ENV),
        "position_tolerance_m": 2.0,
        "velocity_tolerance_m_s": 5.0e-3,
        "tolerance_rationale": (
            "Same degree-8 EGM96-vs-EGM2008 model difference as iss_leo, at the "
            "near-polar 98.2 deg SSO inclination where the J2 nodal precession the "
            "orbit is designed around is strongest."
        ),
    },
    {
        "name": "geo",
        "description": (
            "Geostationary 42,164 km orbit at 0.05 deg, degree-4 gravity plus Sun/Moon "
            "third body and SRP, 1 day — the long-arc SRP/third-body-dominated regime."
        ),
        "position_km": (42164.169, 0.0, 0.0),
        "velocity_km_s": (0.0, 3.0746589515, 0.0026831468),
        "preamble_lines": ("SolarSystem.EphemerisSource = 'DE424';",),
        "spacecraft_lines": (
            "sat.SRPArea = 0.06;",
            "sat.Cr = 1.3;",
            "sat.DryMass = 12.0;",
        ),
        # Mirrored into the fixture's spacecraft block so the Polaris side
        # flies the same ballistic properties GMAT did (see the emission site).
        "spacecraft_srp": {"srp_area_m2": 0.06, "srp_cr": 1.3},
        "force_model_lines": (
            "fm.PrimaryBodies = {Earth};",
            "fm.GravityField.Earth.Degree = 4;",
            "fm.GravityField.Earth.Order = 4;",
            "fm.GravityField.Earth.PotentialFile = 'EGM96.cof';",
            "fm.PointMasses = {Sun, Luna};",
        ),
        "srp_lines": (
            "fm.SRP = On;",
            "fm.SRP.Flux = 1361.0;",
            "fm.SRP.SRPModel = Spherical;",
        ),
        "duration_s": 86400,
        "sample_step_s": 3600,
        "environment": {
            "gravity_degree": 4,
            "gravity_order": 4,
            "third_bodies": ["sun", "moon"],
            "drag_enabled": False,
            "srp_enabled": True,
            "magnetic_field": "none",
        },
        "position_tolerance_m": 0.5,
        "velocity_tolerance_m_s": 5.0e-5,
        "tolerance_rationale": (
            "A full GEO day is SRP- and third-body-dominated. With the fixture's "
            "srp_area_m2/srp_cr flown on both sides (both cannonball, both 1361 W/m2, "
            "no shadow transits in January), measured GMAT-vs-Polaris separation peaks "
            "at 0.017 m -- the sum of the EGM96/EGM2008 degree-4 field difference and "
            "the DE424-vs-DE440-Chebyshev third-body difference. The 0.5 m band carries "
            "~30x margin. History: this band was 150 m until Push 57, absorbing a "
            "disabled force -- the fixture omitted the ballistic properties, "
            "srp_area_m2 defaulted to zero, and the 120 m residual attributed to 'SRP "
            "model differences' was shown by a FreeFlyer force ablation to be the "
            "entire SRP signature. Attribution in a rationale must be backed by an "
            "ablation, not a narrative."
        ),
    },
    {
        "name": "molniya_heo",
        "description": (
            "Molniya HEO: 600 x 39,800 km, 63.4 deg, e=0.74, degree-4 gravity plus "
            "Sun/Moon, ~2 orbits — the high-eccentricity integrator-stress case."
        ),
        "position_km": (6978.137, 0.0, 0.0),
        "velocity_km_s": (0.0, 4.4606637547, 8.9077396834),
        "preamble_lines": ("SolarSystem.EphemerisSource = 'DE424';",),
        "force_model_lines": (
            "fm.PrimaryBodies = {Earth};",
            "fm.GravityField.Earth.Degree = 4;",
            "fm.GravityField.Earth.Order = 4;",
            "fm.GravityField.Earth.PotentialFile = 'EGM96.cof';",
            "fm.PointMasses = {Sun, Luna};",
        ),
        "duration_s": 86000,
        "sample_step_s": 1000,
        "environment": {
            "gravity_degree": 4,
            "gravity_order": 4,
            "third_bodies": ["sun", "moon"],
            "drag_enabled": False,
            "srp_enabled": False,
            "magnetic_field": "none",
        },
        "position_tolerance_m": 25.0,
        "velocity_tolerance_m_s": 1.0e-2,
        "tolerance_rationale": (
            "The e=0.74 orbit sweeps 7,000 km/s at perigee to <1,600 km/s at apogee, "
            "so the two adaptive step controllers place their nodes very differently "
            "and the RK89 truncation no longer cancels the way it does on a circular "
            "orbit — this is the case that stresses step control, not model fidelity. "
            "The 25 m band over two ~12 h orbits is <1e-6 relative near apogee."
        ),
    },
    # --- Attitude kinematics: torque-free spherical-inertia spinner. GMAT's
    # Spinner propagates the attitude kinematically from an initial quaternion +
    # body rate; with a spherical inertia Euler's equation gives omega-dot = 0, so
    # Polaris's rigid-body integrator must reproduce the same constant-rate
    # rotation. This is the independent check on the quaternion kinematics.
    {
        "name": "attitude_spinner",
        "description": (
            "Torque-free spinner: spherical inertia, initial body rate (2, -1, 3) "
            "deg/s about the inertial axes, attitude propagated 300 s. Circular LEO "
            "carrier orbit (two-body) so the state history is defined too."
        ),
        "position_km": (_R_KM, 0.0, 0.0),
        "velocity_km_s": (0.0, _V_CIRC_KM_S, 0.0),
        "spacecraft_lines": (
            "sat.AttitudeCoordinateSystem = EarthMJ2000Eq;",
            "sat.Attitude = Spinner;",
            "sat.AttitudeDisplayStateType = 'Quaternion';",
            "sat.AttitudeRateDisplayStateType = 'AngularVelocity';",
            "sat.Q1 = 0;",
            "sat.Q2 = 0;",
            "sat.Q3 = 0;",
            "sat.Q4 = 1;",
            "sat.AngularVelocityX = 2.0;",
            "sat.AngularVelocityY = -1.0;",
            "sat.AngularVelocityZ = 3.0;",
        ),
        "force_model_lines": ("fm.PointMasses = {Earth};",),
        "extra_report_params": ("sat.Q1", "sat.Q2", "sat.Q3", "sat.Q4"),
        "duration_s": 300,
        "sample_step_s": 30,
        "environment": {
            "gravity_degree": 0,
            "gravity_order": -1,
            "third_bodies": [],
            "drag_enabled": False,
            "srp_enabled": False,
            "magnetic_field": "none",
        },
        # Spherical inertia (kg m^2) and the deg/s -> rad/s initial rate; the C++
        # side reads these to configure the attitude propagation.
        "attitude": {
            "spherical_inertia_kg_m2": 0.1,
            "body_rate_rad_s": [
                2.0 * 0.017453292519943295,
                -1.0 * 0.017453292519943295,
                3.0 * 0.017453292519943295,
            ],
        },
        "position_tolerance_m": 0.05,
        "velocity_tolerance_m_s": 1.0e-4,
        "attitude_tolerance_deg": 1.0e-3,
        "tolerance_rationale": (
            "Two-body carrier orbit (position band as two_body). The attitude is a "
            "constant-rate rotation both sides compute independently; 1e-3 deg over "
            "300 s covers GMAT's quaternion-report rounding and the small deg/s->rad/s "
            "conversion, far below any physical claim."
        ),
    },
)


def regenerate_propagation_fixture(
    gmat_console: str,
    workdir: str,
    cases: tuple[dict, ...] = PROPAGATION_CASES,
    timeout_s: float = 600.0,
    script_dir: str | None = None,
) -> dict:
    """Run GMAT once per case to regenerate the propagation fixture dict.

    Emits each case's script into @p workdir (or @p script_dir, when the generated
    scripts should also be committed), runs ``GmatConsole`` on it, and parses the
    reports into the fixture. Requires the GMAT binary — callers must gate on its
    presence. Raises ``RuntimeError`` if GMAT produces no report for a case.
    """
    work = Path(workdir)
    samples_by_case: dict[str, list[dict]] = {}
    for case in cases:
        report_path = work / f"prop_{case['name']}_report.txt"
        script_path = work / f"prop_{case['name']}.script"
        script = write_propagation_script(case, str(report_path.resolve()))
        script_path.write_text(script)
        if script_dir is not None:
            (Path(script_dir) / f"prop_{case['name']}.script").write_text(script)
        report_path.unlink(missing_ok=True)
        # GMAT resolves gmat_startup_file.txt and ../data/... relative to its own
        # bin/, so it must run from there; script/report paths are absolute.
        result = subprocess.run(  # noqa: S603 — console path is operator-supplied, not user input
            [gmat_console, "--run", str(script_path.resolve())],
            cwd=str(Path(gmat_console).resolve().parent),
            capture_output=True,
            text=True,
            timeout=timeout_s,
            check=False,
        )
        if not report_path.exists():
            raise RuntimeError(
                f"GMAT produced no report at {report_path} (exit={result.returncode}).\n"
                f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
            )
        samples_by_case[case["name"]] = samples_from_rows(
            parse_report(report_path.read_text())
        )
    return build_propagation_fixture(cases, samples_by_case)


def compare_propagation(committed: dict, regenerated: dict) -> list[str]:
    """Return drift messages; empty means GMAT agrees with the committed fixture.

    Each committed sample must be reproduced by GMAT at the same elapsed time and
    within the case's declared position/velocity tolerance bands.
    """

    def index(fixture: dict) -> dict:
        return {case["name"]: case for case in fixture["cases"]}

    want, got = index(committed), index(regenerated)
    messages: list[str] = []
    for name, case in want.items():
        if name not in got:
            messages.append(f"{name}: missing from GMAT regeneration")
            continue
        fresh = got[name]["samples"]
        if len(fresh) != len(case["samples"]):
            messages.append(
                f"{name}: GMAT returned {len(fresh)} samples, committed has "
                f"{len(case['samples'])}"
            )
            continue
        for old, new in zip(case["samples"], fresh):
            # The stop-condition overshoot is ~0.4 us and reproducible; a shifted
            # sample time means the grid changed, which invalidates the comparison.
            if abs(old["t_s"] - new["t_s"]) > 1.0e-3:
                messages.append(
                    f"{name} t={old['t_s']}: GMAT sampled t={new['t_s']} instead"
                )
                continue
            for field, tol_key in (
                ("position_m", "position_tolerance_m"),
                ("velocity_m_s", "velocity_tolerance_m_s"),
            ):
                diff = max(abs(a - b) for a, b in zip(old[field], new[field]))
                tol = case[tol_key]
                if diff > tol:
                    messages.append(
                        f"{name} t={old['t_s']} {field}: committed {old[field]} vs "
                        f"GMAT {new[field]} (max|Δ|={diff:.3e} > tol {tol:.1e})"
                    )
    return messages
