/// @file Cross-validation of the Polaris propagator against GMAT
/// (REQ-VV-002; design doc §23.1).
///
/// Replays `tests/golden/gmat_propagation.json` — states GMAT produced for the
/// same initial conditions and force model — through `SimRunner` and compares
/// position and velocity within per-case tolerance bands recorded in the fixture
/// itself.
///
/// **This is the only test in the repo that can catch a systematically wrong
/// model.** Every other check here is a self-consistency property: energy and
/// angular momentum conservation, orbit closure, frame round-trips. Those are
/// strong against sign errors, unit slips, and wiring mistakes, but they are
/// structurally blind to a force model that is smoothly, consistently wrong — a
/// mis-scaled harmonic coefficient or a field referenced to the wrong pole is
/// still perfectly conservative, so it conserves energy to machine precision
/// while putting the vehicle in the wrong place.
///
/// That is not hypothetical. Standing this test up immediately surfaced two real
/// defects in already-merged, already-reviewed code: the zonal gravity field was
/// evaluated about the J2000 pole rather than Earth's true pole (~100 m per
/// revolution in LEO), and the field was built with WGS84's GM and reference
/// radius instead of the values the EGM2008 coefficients were actually solved
/// with. Both had passed every conservation check.
///
/// Sampling uses `SimRunner::runAt` at GMAT's *actual* reported elapsed times.
/// GMAT's stop conditions overshoot slightly — its "600 s" sample is really
/// 600.0000003841706 s — and at 7.6 km/s that is ~3 mm, the same size as the
/// two-body residual being measured. Comparing at nominal times would fold the
/// reference tool's timing into the answer.
///
/// The fixture is regenerated by `python -m gmat regenerate-propagation`, which
/// needs GMAT installed; this test only reads the committed file, so the normal
/// test path has no GMAT dependency.

#include <gtest/gtest.h>

#include <cmath>
#include <Eigen/Core>
#include <fstream>
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

#include "math/frames.hpp"
#include "math/typed_vector.hpp"
#include "scenario/sim_config.hpp"
#include "scenario/sim_runner.hpp"
#include "time/leap_seconds.hpp"
#include "time/utc.hpp"

namespace {

namespace scenario = polaris::sim::scenario;
namespace pm = polaris::math;
namespace pt = polaris::time;
using nlohmann::json;

Eigen::Vector3d vec3(const json& node) {
  return Eigen::Vector3d(node[0].get<double>(), node[1].get<double>(), node[2].get<double>());
}

/// Build the Polaris-side configuration for one fixture case.
scenario::SimConfig configFor(const json& c, const pt::LeapSecondTable& leap) {
  scenario::SimConfig config;
  config.scenario_name = c.at("name").get<std::string>();
  config.spacecraft.name = "gmat-crossval";

  const json& sc = c.at("spacecraft");
  config.spacecraft.mass_kg = sc.at("mass_kg").get<double>();
  const json& inertia = sc.at("inertia_kgm2");
  config.spacecraft.inertia_kgm2 =
      Eigen::Vector3d(inertia.at("ixx").get<double>(), inertia.at("iyy").get<double>(),
                      inertia.at("izz").get<double>())
          .asDiagonal();

  const json& env = c.at("environment");
  config.environment.gravity_degree = env.at("gravity_degree").get<int>();
  config.environment.gravity_order = env.value("gravity_order", -1);
  config.environment.drag_enabled = env.value("drag_enabled", false);
  config.environment.srp_enabled = env.value("srp_enabled", false);
  config.environment.magnetic_field = scenario::MagneticModel::kNone;
  for (const json& body : env.at("third_bodies")) {
    const std::string name = body.get<std::string>();
    if (name == "sun") {
      config.environment.sun_third_body = true;
    } else if (name == "moon") {
      config.environment.moon_third_body = true;
    }
  }

  // Parse the epoch through the same path the sim uses, so a fixture epoch and a
  // scenario epoch cannot be interpreted differently.
  const std::string epoch_text = c.at("epoch_utc").get<std::string>();
  pt::UtcDateTime utc;
  int year = 0;
  unsigned month = 0;
  unsigned day = 0;
  unsigned hour = 0;
  unsigned minute = 0;
  double second = 0.0;
  EXPECT_EQ(std::sscanf(epoch_text.c_str(), "%4d-%2u-%2uT%2u:%2u:%lfZ", &year, &month, &day, &hour,
                        &minute, &second),
            6)
      << epoch_text;
  utc.year = year;
  utc.month = month;
  utc.day = day;
  utc.hour = hour;
  utc.minute = minute;
  utc.second = static_cast<unsigned>(second);
  config.initial_state.epoch = pt::taiFromUtc(utc, leap);

  const json& init = c.at("initial_state");
  config.initial_state.position = pm::Vec3<pm::frames::ECI>(vec3(init.at("position_m")));
  config.initial_state.velocity = pm::Vec3<pm::frames::ECI>(vec3(init.at("velocity_m_s")));
  config.initial_state.attitude = pm::Quat<pm::frames::Body, pm::frames::ECI>::Identity();
  config.initial_state.body_rate = pm::Vec3<pm::frames::Body>(Eigen::Vector3d::Zero());

  // Tight tolerances: the residual being measured is centimetres, so integrator
  // error must sit well below it or it would be indistinguishable from model
  // disagreement.
  config.propagation.abs_tol = 1.0e-13;
  config.propagation.rel_tol = 1.0e-13;
  config.propagation.max_step_s = 300.0;
  config.propagation.duration_s = c.at("samples").back().at("t_s").get<double>();
  config.propagation.output_step_s = config.propagation.duration_s;
  return config;
}

}  // namespace

TEST(GmatPropagation, PolarisAgreesWithGmatAcrossForceModels) {
  RecordProperty("verifies", "REQ-VV-002");

  std::ifstream file(std::string(GOLDEN_DIR) + "/gmat_propagation.json");
  ASSERT_TRUE(file.good()) << "cannot open gmat_propagation.json";
  json fixture;
  ASSERT_NO_THROW(file >> fixture);

  const pt::LeapSecondTable leap = pt::LeapSecondTable::historical();
  const scenario::DataPaths paths = scenario::DataPaths::under(GOLDEN_DIR);

  const json& cases = fixture.at("cases");
  ASSERT_FALSE(cases.empty());

  for (const json& c : cases) {
    const std::string name = c.at("name").get<std::string>();
    SCOPED_TRACE("case: " + name);

    const scenario::SimConfig config = configFor(c, leap);
    scenario::SimRunner runner;
    std::string error;
    ASSERT_TRUE(runner.build(config, paths, &error)) << error;

    std::vector<double> times;
    for (const json& sample : c.at("samples")) {
      times.push_back(sample.at("t_s").get<double>());
    }
    std::vector<scenario::TrajectorySample> trajectory;
    ASSERT_TRUE(runner.runAt(times, trajectory, &error)) << error;
    ASSERT_EQ(trajectory.size(), c.at("samples").size());

    const double position_tolerance = c.at("position_tolerance_m").get<double>();
    const double velocity_tolerance = c.at("velocity_tolerance_m_s").get<double>();

    double worst_position = 0.0;
    double worst_velocity = 0.0;
    for (std::size_t i = 0; i < trajectory.size(); ++i) {
      const json& expected = c.at("samples")[i];
      const double dr =
          (trajectory[i].state.position.eigen() - vec3(expected.at("position_m"))).norm();
      const double dv =
          (trajectory[i].state.velocity.eigen() - vec3(expected.at("velocity_m_s"))).norm();
      worst_position = std::max(worst_position, dr);
      worst_velocity = std::max(worst_velocity, dv);
      EXPECT_LT(dr, position_tolerance) << "t=" << trajectory[i].t_s << " s";
      EXPECT_LT(dv, velocity_tolerance) << "t=" << trajectory[i].t_s << " s";
    }

    // Report the achieved margin so a slow drift toward the band shows up in CI
    // output before it becomes a failure.
    RecordProperty(name + "_worst_position_m", std::to_string(worst_position));
    RecordProperty(name + "_worst_velocity_m_s", std::to_string(worst_velocity));

    // A tolerance far looser than the achieved error is a band that has stopped
    // testing anything. This is deliberately generous (100x) so it flags only
    // genuinely vacuous bands, not ordinary headroom. The 100x factor and the
    // per-case position_tolerance_m bands are coupled: if a band is ever widened,
    // this guard must stay below it, so re-check both together when retuning.
    EXPECT_GT(worst_position * 100.0, position_tolerance)
        << "case '" << name << "' achieves " << worst_position << " m against a "
        << position_tolerance << " m band — the tolerance is too loose to be meaningful";
  }
}
