#ifndef POLARIS_SIM_WORLD_NRLMSIS_HPP
#define POLARIS_SIM_WORLD_NRLMSIS_HPP

/// @file
/// @brief NRLMSIS 2.1 neutral density — the truth atmosphere (REQ-SIM-002).
///
/// The high-fidelity `DensityFn` (`atmosphere.hpp`). Where `exponentialDensity()`
/// is a static fit that only knows altitude, NRLMSIS is an empirical
/// whole-atmosphere model driven by solar and geomagnetic activity, and it
/// resolves the variation the exponential model cannot see at all: the diurnal
/// bulge (density peaks mid-afternoon local solar time), the seasonal-latitudinal
/// structure, and the order-of-magnitude thermospheric swing between solar
/// minimum and maximum. Above ~200 km that swing dominates the drag error budget,
/// which is why the exponential model is a baseline and this is the truth model.
///
/// Paying for that fidelity means this model needs strictly more context than the
/// exponential one, and all of it is injected rather than assumed:
///  - **ECI->ECEF** (`setEciToEcef`), because MSIS is evaluated at a geodetic
///    latitude and longitude. Longitude is what fixes local solar time, so unlike
///    the drag model itself this genuinely cannot avoid the Earth-rotation
///    reduction.
///  - **Leap seconds** (`setLeapSeconds`), to get day-of-year and UT seconds from
///    the state's TAI epoch. UTC is used where the model wants UT1; they differ
///    by under 0.9 s, far below anything the atmosphere resolves.
///  - **Space weather** (`setSpaceWeatherSource`), the F10.7 and Ap drivers,
///    resolved per epoch from the committed CelesTrak `SW-All.csv`
///    (`space_weather_file.hpp`) so a run tracks the real solar cycle. A static
///    `setSpaceWeather` snapshot (moderate-activity default) is the fallback when
///    no file source is wired.
///
/// Any of these missing means the model reports zero density — "no atmosphere
/// here" — rather than silently substituting a guess, so a half-wired sim
/// produces obviously-zero drag instead of plausibly-wrong drag.
///
/// **Licensing (important).** NRLMSIS is under NRL's MSIS(R) Open Source Academic
/// Research License Agreement: research, academic and non-profit use only, and it
/// forbids selling or licensing derivative works — or data products generated by
/// the model — for a fee without NRL's written consent. Polaris's commercial tier
/// (`LICENSING.md`) is incompatible with shipping it, so **MSIS must be removed,
/// or NRL consent obtained, before any Polaris commercial license is sold.** The
/// source is fetched at configure time and never committed
/// (`cmake/Dependencies.cmake`), so that removal is deleting a CMake block and
/// these two files, not rewriting git history. See `THIRD_PARTY_NOTICES.md`.
///
/// This software incorporates the MSIS(R) empirical atmospheric model software
/// designed and provided by NRL. Use is governed by the Open Source Academic
/// Research License Agreement contained in the file nrlmsis2.1_license.txt.
///
/// **Process-global model state.** NRLMSIS keeps its coefficients and its
/// evaluation cache in Fortran module `save` storage, so despite this class
/// looking like an ordinary object, the model behind it is a process-wide
/// singleton:
///  - `density()` serializes on a **process-wide** mutex, not a per-object one —
///    a per-object mutex would guard nothing, since two instances share the same
///    `save` variables. Concurrent use is safe but never parallel.
///  - Only **one coefficient set can be live per process**. Constructing a second
///    instance with a *different* `parm_path` would silently repoint every
///    existing instance, so it is refused: the second construction fails with
///    `good() == false` rather than corrupting the first. Reusing the same path
///    is fine and simply shares the already-loaded coefficients.
///
/// References:
///  - Emmert et al., "NRLMSIS 2.0: A Whole-Atmosphere Empirical Model...",
///    Earth and Space Science 8, 2021. [emmert2021]
///  - Vallado, 4th ed., §8.6.2 (drag and atmosphere models). [vallado2013]

#include <array>
#include <functional>
#include <mutex>
#include <string>

#include "math/frames.hpp"
#include "math/quaternion.hpp"
#include "math/typed_vector.hpp"
#include "time/leap_seconds.hpp"
#include "time/timescales.hpp"
#include "world/atmosphere.hpp"

namespace polaris::sim::world {

/// The solar and geomagnetic activity drivers MSIS consumes.
struct SpaceWeather {
  /// 81-day centered average F10.7 solar radio flux [sfu].
  double f107a{150.0};
  /// Daily F10.7 for the previous day [sfu].
  double f107{150.0};
  /// Geomagnetic index array; only `ap[0]` (the daily Ap) is used unless the
  /// model's storm-time switches are enabled. Layout per `msis_calc.F90`.
  std::array<double, 7> ap{{4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0}};
};

/// NRLMSIS 2.1 wrapper exposing the shared `DensityFn` contract.
class NrlmsisAtmosphere {
 public:
  /// Resolver for the ECI->ECEF rotation at a TAI epoch — the same contract
  /// `SphericalHarmonicGravity::setEciToEcef` takes, so one lambda drives both.
  using EciToEcefFn =
      std::function<bool(const time::Tai&, math::Quat<math::frames::ECEF, math::frames::ECI>&)>;

  /// Loads the coefficient file. Check `good()` before use — a construction that
  /// could not read the file leaves the model permanently reporting zero density
  /// rather than throwing mid-setup.
  ///
  /// @param parm_path Path to `msis21.parm`. Defaults to the copy CMake located
  ///                  in the fetched upstream tree (`POLARIS_MSIS_PARM_PATH`).
  ///                  Constructing with a path different from an already-loaded
  ///                  one fails (see the process-global note above).
  explicit NrlmsisAtmosphere(const std::string& parm_path = defaultParmPath());

  /// True if the coefficient file loaded and the model can be evaluated.
  bool good() const { return initialized_; }

  /// Why `good()` is false, for diagnostics. Empty when healthy.
  const std::string& error() const { return error_; }

  void setEciToEcef(EciToEcefFn fn) { eci_to_ecef_ = std::move(fn); }

  void setLeapSeconds(const time::LeapSecondTable* leap) { leap_ = leap; }

  void setSpaceWeather(const SpaceWeather& sw) { space_weather_ = sw; }

  const SpaceWeather& spaceWeather() const { return space_weather_; }

  /// Resolver for time-varying space weather at a TAI epoch — the file layer
  /// (`space_weather_file.hpp`) drives this so a run tracks the real solar cycle
  /// and geomagnetic history instead of one fixed snapshot. When set it takes
  /// precedence over the static `setSpaceWeather` value; returning false for an
  /// epoch outside the loaded coverage yields zero density there, consistent with
  /// the model's other missing-input behaviour.
  using SpaceWeatherFn = std::function<bool(const time::Tai&, SpaceWeather&)>;

  void setSpaceWeatherSource(SpaceWeatherFn fn) { space_weather_fn_ = std::move(fn); }

  /// Total neutral mass density [kg/m^3]. Zero if the model is not initialized,
  /// a resolver is missing, or the point is outside the model's domain.
  double density(const time::Tai& epoch, const math::Vec3<math::frames::ECI>& r_eci) const;

  /// Bind to the shared `DensityFn` contract for `AtmosphericDrag`. The returned
  /// callable holds a pointer to this object, which must outlive it.
  DensityFn densityFn() const {
    return [this](const time::Tai& t, const math::Vec3<math::frames::ECI>& r) {
      return density(t, r);
    };
  }

  /// Compile-time path to the fetched `msis21.parm` (`POLARIS_MSIS_PARM_PATH`).
  static std::string defaultParmPath();

 private:
  bool initialized_{false};
  std::string error_;
  EciToEcefFn eci_to_ecef_;
  const time::LeapSecondTable* leap_{nullptr};
  SpaceWeather space_weather_{};
  SpaceWeatherFn space_weather_fn_;
};

}  // namespace polaris::sim::world

#endif  // POLARIS_SIM_WORLD_NRLMSIS_HPP
