/// @file Unit tests for the IGRF-14 main field and its IAGA coefficient loader
/// (REQ-SIM-002; design doc §5.2, §6.2, §3.7).
///
/// Three layers, deliberately independent of one another:
///
///  - **Golden.** The evaluator is checked against `igrf14_reference.csv`,
///    generated by the official IAGA reference implementation (pyIGRF14). This
///    is the only test that can catch a wrong Legendre recursion, and it covers
///    both poles, the SV-extrapolation window, and radii from the surface to GEO.
///
///  - **Physics.** Facts about Earth's field that hold independently of IGRF —
///    surface magnitude between roughly 22 and 67 µT, the field about twice as
///    strong at the poles as at the equator, a ~1/r³ falloff, and a dipole axis
///    tilted about 11° from the spin axis. A fixture that parsed but held
///    garbage — wrong units, transposed indices, nT read as T — fails these even
///    if the golden file were also wrong.
///
///  - **Loader.** Ordinary parser tests, plus the one property that is not
///    obvious: collapsing a bracketing epoch pair into a base-plus-rate snapshot
///    must reproduce the model's linear interpolation *exactly*, not
///    approximately, since the evaluator never sees the grid.

#include "environment/igrf.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <cstdio>
#include <Eigen/Core>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "math/frames.hpp"
#include "math/typed_vector.hpp"
#include "world/igrf_file.hpp"

namespace {

namespace env = polaris::environment;
namespace world = polaris::sim::world;
namespace pm = polaris::math;

constexpr double kDeg = M_PI / 180.0;
constexpr double kTesla = 1.0e-9;  ///< nT expressed in T, for readable bounds.

/// The committed IAGA coefficient file.
std::string coeffsPath() {
  return POLARIS_IGRF_COEFFS;
}

/// Load the snapshot for @p year or fail the calling test.
env::IgrfCoefficients loadOrFail(double year) {
  env::IgrfCoefficients c{};
  std::string error;
  EXPECT_TRUE(world::loadIgrfFile(coeffsPath(), year, c, &error)) << error;
  return c;
}

/// One row of the pyIGRF14-generated reference fixture.
struct ReferenceRow {
  double radius_km{};
  double colatitude_deg{};
  double longitude_deg{};
  double decimal_year{};
  double br_nt{};
  double btheta_nt{};
  double bphi_nt{};
};

std::vector<ReferenceRow> loadReference() {
  std::vector<ReferenceRow> rows;
  std::ifstream file(POLARIS_IGRF_REFERENCE);
  EXPECT_TRUE(file.good()) << "cannot open " << POLARIS_IGRF_REFERENCE;
  std::string line;
  while (std::getline(file, line)) {
    if (line.empty() || line[0] == '#' || line[0] == 'r') {  // comments + header row
      continue;
    }
    for (char& c : line) {
      if (c == ',') {
        c = ' ';
      }
    }
    std::istringstream in(line);
    ReferenceRow r;
    if (in >> r.radius_km >> r.colatitude_deg >> r.longitude_deg >> r.decimal_year >> r.br_nt >>
        r.btheta_nt >> r.bphi_nt) {
      rows.push_back(r);
    }
  }
  return rows;
}

/// Write @p text to a scratch file and return its path. The caller removes it.
std::string writeTemp(const std::string& name, const std::string& text) {
  const std::string path = testing::TempDir() + "/" + name;
  std::ofstream out(path);
  out << text;
  return path;
}

}  // namespace

// --- Golden: the IAGA reference implementation -------------------------------

TEST(IgrfGolden, MatchesIagaReferenceImplementation) {
  const std::vector<ReferenceRow> rows = loadReference();
  ASSERT_FALSE(rows.empty()) << "reference fixture is empty";

  // Both sides evaluate the same coefficients through the same recursion, so
  // agreement is limited by round-off and by the 17-digit fixture, not by
  // modelling. 1 pT on fields of tens of µT is ~1e-7 relative — tight enough
  // that a genuinely wrong recursion cannot slip through, loose enough to
  // survive a different summation order.
  constexpr double kToleranceT = 1.0e-12;

  int checked = 0;
  for (const ReferenceRow& r : rows) {
    const env::IgrfField field(loadOrFail(r.decimal_year));
    ASSERT_TRUE(field.good());

    double b_r = 0.0;
    double b_theta = 0.0;
    double b_phi = 0.0;
    ASSERT_TRUE(field.fieldSpherical(r.radius_km * 1000.0, r.colatitude_deg * kDeg,
                                     r.longitude_deg * kDeg, r.decimal_year, b_r, b_theta, b_phi));

    SCOPED_TRACE(
        "r=" + std::to_string(r.radius_km) + "km theta=" + std::to_string(r.colatitude_deg) +
        " phi=" + std::to_string(r.longitude_deg) + " year=" + std::to_string(r.decimal_year));
    EXPECT_NEAR(b_r, r.br_nt * kTesla, kToleranceT);
    EXPECT_NEAR(b_theta, r.btheta_nt * kTesla, kToleranceT);
    EXPECT_NEAR(b_phi, r.bphi_nt * kTesla, kToleranceT);
    ++checked;
  }
  EXPECT_GE(checked, 50) << "reference fixture too small to be meaningful";
}

// --- Physics: independent of IGRF itself -------------------------------------

TEST(Igrf, SurfaceMagnitudeIsInTheKnownRange) {
  const env::IgrfField field(loadOrFail(2026.5));
  // Earth's surface field spans roughly 22 µT (the South Atlantic Anomaly) to
  // 67 µT (near the magnetic poles). Anything outside that means a unit or
  // normalisation error, not a modelling nuance.
  for (int colat_deg = 1; colat_deg < 180; colat_deg += 7) {
    for (int lon_deg = -180; lon_deg < 180; lon_deg += 23) {
      double b_r = 0.0;
      double b_theta = 0.0;
      double b_phi = 0.0;
      ASSERT_TRUE(field.fieldSpherical(env::kIgrfReferenceRadius, colat_deg * kDeg, lon_deg * kDeg,
                                       2026.5, b_r, b_theta, b_phi));
      const double magnitude = std::sqrt(b_r * b_r + b_theta * b_theta + b_phi * b_phi);
      SCOPED_TRACE("colat=" + std::to_string(colat_deg) + " lon=" + std::to_string(lon_deg));
      EXPECT_GT(magnitude, 20.0e-6);
      EXPECT_LT(magnitude, 70.0e-6);
    }
  }
}

TEST(Igrf, PolarFieldIsAboutTwiceTheEquatorialField) {
  const env::IgrfField field(loadOrFail(2026.5));
  auto magnitude = [&](double colat_deg, double lon_deg) {
    double b_r = 0.0;
    double b_theta = 0.0;
    double b_phi = 0.0;
    EXPECT_TRUE(field.fieldSpherical(env::kIgrfReferenceRadius, colat_deg * kDeg, lon_deg * kDeg,
                                     2026.5, b_r, b_theta, b_phi));
    return std::sqrt(b_r * b_r + b_theta * b_theta + b_phi * b_phi);
  };
  // A dipole gives |B|(pole) = 2|B|(equator) exactly; the real field departs from
  // that by tens of percent, so this is a loose but genuinely diagnostic bound.
  const double ratio = 0.5 * (magnitude(1.0, 0.0) + magnitude(179.0, 0.0)) / magnitude(90.0, 0.0);
  EXPECT_GT(ratio, 1.5);
  EXPECT_LT(ratio, 2.6);
}

TEST(Igrf, FallsOffAsInverseCubeAtLargeRadius) {
  const env::IgrfField field(loadOrFail(2026.5));
  auto magnitude = [&](double radius_m) {
    double b_r = 0.0;
    double b_theta = 0.0;
    double b_phi = 0.0;
    EXPECT_TRUE(
        field.fieldSpherical(radius_m, 40.0 * kDeg, 10.0 * kDeg, 2026.5, b_r, b_theta, b_phi));
    return std::sqrt(b_r * b_r + b_theta * b_theta + b_phi * b_phi);
  };
  // Far from the surface the n=1 dipole dominates and |B| ~ r^-3; higher
  // harmonics fall off faster, so the ratio approaches 8 from above as r grows.
  const double near = magnitude(20.0 * env::kIgrfReferenceRadius);
  const double far = magnitude(40.0 * env::kIgrfReferenceRadius);
  EXPECT_NEAR(near / far, 8.0, 0.05);
}

TEST(Igrf, DipoleAxisIsTiltedAboutElevenDegrees) {
  const env::IgrfCoefficients c = loadOrFail(2026.5);
  // The geomagnetic dipole tilt is atan(sqrt(g11^2 + h11^2) / g10) — a textbook
  // ~11 deg. This pins the n=1 coefficients specifically, so a transposed [n][m]
  // index or a dropped h table shows up here rather than as a subtle bias.
  const double tilt = std::atan2(std::hypot(c.g[1][1], c.h[1][1]), std::abs(c.g[1][0])) / kDeg;
  EXPECT_GT(tilt, 9.0);
  EXPECT_LT(tilt, 13.0);
}

TEST(Igrf, CartesianMagnitudeMatchesSphericalMagnitude) {
  const env::IgrfField field(loadOrFail(2026.5));
  const double radius = env::kIgrfReferenceRadius + 500.0e3;
  const double colat = 55.0 * kDeg;
  const double lon = -73.0 * kDeg;

  double b_r = 0.0;
  double b_theta = 0.0;
  double b_phi = 0.0;
  ASSERT_TRUE(field.fieldSpherical(radius, colat, lon, 2026.5, b_r, b_theta, b_phi));

  const Eigen::Vector3d r_vec(radius * std::sin(colat) * std::cos(lon),
                              radius * std::sin(colat) * std::sin(lon), radius * std::cos(colat));
  pm::Vec3<pm::frames::ECEF> b_ecef;
  ASSERT_TRUE(field.field(pm::Vec3<pm::frames::ECEF>(r_vec), 2026.5, b_ecef));

  // The spherical->Cartesian rotation is orthonormal, so magnitude is invariant.
  EXPECT_NEAR(b_ecef.eigen().norm(), std::sqrt(b_r * b_r + b_theta * b_theta + b_phi * b_phi),
              1.0e-15);
  // And the radial component is the projection onto r̂.
  EXPECT_NEAR(b_ecef.eigen().dot(r_vec.normalized()), b_r, 1.0e-15);
}

TEST(Igrf, FieldIsFiniteExactlyAtBothPoles) {
  const env::IgrfField field(loadOrFail(2026.5));
  // B_phi carries a P_n^m / sin(theta), which is 0/0 at the poles. The limit is
  // finite, so an implementation that simply divides produces NaN here.
  for (const double colat : {0.0, M_PI}) {
    double b_r = 0.0;
    double b_theta = 0.0;
    double b_phi = 0.0;
    ASSERT_TRUE(
        field.fieldSpherical(env::kIgrfReferenceRadius, colat, 0.4, 2026.5, b_r, b_theta, b_phi));
    SCOPED_TRACE("colatitude=" + std::to_string(colat));
    EXPECT_TRUE(std::isfinite(b_r));
    EXPECT_TRUE(std::isfinite(b_theta));
    EXPECT_TRUE(std::isfinite(b_phi));
    // Approaching the pole must converge to the value at it — i.e. the limit
    // branch and the ordinary P/sin(theta) branch agree, rather than the limit
    // being a plausible-looking but different number.
    //
    // The bound is set by the field's own gradient, not by round-off: |dB/dtheta|
    // is of the same order as |B| itself (~5e-5 T per radian), so over a 1e-8 rad
    // offset the field genuinely moves ~5e-13 T. 1e-11 leaves ~20x headroom over
    // that while still being seven orders below the field magnitude — a limit
    // branch that was actually wrong would miss by far more than this.
    constexpr double kProbeOffset = 1.0e-8;
    double nb_r = 0.0;
    double nb_theta = 0.0;
    double nb_phi = 0.0;
    const double nearby = colat == 0.0 ? kProbeOffset : M_PI - kProbeOffset;
    ASSERT_TRUE(field.fieldSpherical(env::kIgrfReferenceRadius, nearby, 0.4, 2026.5, nb_r, nb_theta,
                                     nb_phi));
    EXPECT_NEAR(b_r, nb_r, 1.0e-11);
    EXPECT_NEAR(b_theta, nb_theta, 1.0e-11);
    EXPECT_NEAR(b_phi, nb_phi, 1.0e-11);
  }
}

TEST(Igrf, SecularVariationMovesTheFieldOverAYear) {
  const env::IgrfField field(loadOrFail(2026.0));
  auto radial = [&](double year) {
    double b_r = 0.0;
    double b_theta = 0.0;
    double b_phi = 0.0;
    EXPECT_TRUE(field.fieldSpherical(env::kIgrfReferenceRadius, 60.0 * kDeg, 20.0 * kDeg, year, b_r,
                                     b_theta, b_phi));
    return b_r;
  };
  // Secular variation is tens of nT/yr — small against a ~50 µT field but far
  // above round-off. Both bounds matter: too small means SV was dropped, too
  // large means it was applied with the wrong scale.
  const double drift = std::abs(radial(2027.0) - radial(2026.0));
  EXPECT_GT(drift, 1.0e-9);
  EXPECT_LT(drift, 1.0e-6);
}

// --- Evaluator guards --------------------------------------------------------

TEST(Igrf, RejectsStructurallyInvalidCoefficients) {
  env::IgrfCoefficients c{};
  c.epoch_year = 2025.0;
  c.degree = 0;  // below the minimum
  const env::IgrfField field(c);
  EXPECT_FALSE(field.good());

  double b_r = 1.0;
  double b_theta = 2.0;
  double b_phi = 3.0;
  EXPECT_FALSE(
      field.fieldSpherical(env::kIgrfReferenceRadius, 1.0, 1.0, 2026.0, b_r, b_theta, b_phi));
  // Outputs untouched on refusal, so a caller that ignores the return value at
  // least does not read a half-written field.
  EXPECT_EQ(b_r, 1.0);
  EXPECT_EQ(b_theta, 2.0);
  EXPECT_EQ(b_phi, 3.0);
}

TEST(Igrf, RejectsNonFiniteAndNonPositiveInputs) {
  const env::IgrfField field(loadOrFail(2026.5));
  double b_r = 0.0;
  double b_theta = 0.0;
  double b_phi = 0.0;
  const double nan = std::nan("");
  EXPECT_FALSE(field.fieldSpherical(0.0, 1.0, 1.0, 2026.0, b_r, b_theta, b_phi));
  EXPECT_FALSE(field.fieldSpherical(-1.0, 1.0, 1.0, 2026.0, b_r, b_theta, b_phi));
  EXPECT_FALSE(
      field.fieldSpherical(env::kIgrfReferenceRadius, nan, 1.0, 2026.0, b_r, b_theta, b_phi));
  EXPECT_FALSE(
      field.fieldSpherical(env::kIgrfReferenceRadius, 1.0, nan, 2026.0, b_r, b_theta, b_phi));
  EXPECT_FALSE(field.fieldSpherical(env::kIgrfReferenceRadius, 1.0, 1.0, nan, b_r, b_theta, b_phi));

  pm::Vec3<pm::frames::ECEF> out;
  EXPECT_FALSE(field.field(pm::Vec3<pm::frames::ECEF>(Eigen::Vector3d::Zero()), 2026.0, out));
}

// --- Loader ------------------------------------------------------------------

TEST(IgrfFile, LoadsTheCommittedIagaFile) {
  const env::IgrfCoefficients c = loadOrFail(2026.5);
  EXPECT_EQ(c.degree, env::kIgrfMaxDegree);
  EXPECT_DOUBLE_EQ(c.epoch_year, 2025.0);
  // h_n^0 is identically zero by definition — sin(0*phi) vanishes — so the file
  // must never have populated it.
  for (int n = 1; n <= c.degree; ++n) {
    EXPECT_EQ(c.h[n][0], 0.0) << "n=" << n;
  }
  // The axial dipole is large and negative (field points from geographic south
  // to north), around -29 350 nT at 2025.0.
  EXPECT_NEAR(c.g[1][0], -29350.0, 1.0);
}

TEST(IgrfFile, SnapshotReproducesGridInterpolationExactly) {
  // Loading at 2017.5 collapses the 2015/2020 pair into base+rate. Evaluated at
  // 2020.0 that must land exactly on the 2020.0 column, which is what loading at
  // 2020.0 returns directly. This is the property the whole snapshot design
  // rests on: the evaluator never sees the epoch grid, so if the collapse were
  // merely approximate every date inside an interval would carry a quiet bias.
  const env::IgrfField interpolated(loadOrFail(2017.5));
  const env::IgrfField direct(loadOrFail(2020.0));

  double ib_r = 0.0;
  double ib_theta = 0.0;
  double ib_phi = 0.0;
  double db_r = 0.0;
  double db_theta = 0.0;
  double db_phi = 0.0;
  const double radius = env::kIgrfReferenceRadius + 700.0e3;
  ASSERT_TRUE(interpolated.fieldSpherical(radius, 1.1, -2.0, 2020.0, ib_r, ib_theta, ib_phi));
  ASSERT_TRUE(direct.fieldSpherical(radius, 1.1, -2.0, 2020.0, db_r, db_theta, db_phi));

  EXPECT_NEAR(ib_r, db_r, 1.0e-15);
  EXPECT_NEAR(ib_theta, db_theta, 1.0e-15);
  EXPECT_NEAR(ib_phi, db_phi, 1.0e-15);
}

TEST(IgrfFile, PastTheLastEpochUsesThePublishedSecularVariation) {
  const env::IgrfCoefficients c = loadOrFail(2028.0);
  EXPECT_DOUBLE_EQ(c.epoch_year, 2025.0);
  // The published SV column stops at degree 8; higher degrees are held constant.
  EXPECT_EQ(c.sv_degree, env::kIgrfMaxSvDegree);
  EXPECT_NEAR(c.g_sv[1][0], 12.6, 1.0e-9);
  for (int n = env::kIgrfMaxSvDegree + 1; n <= c.degree; ++n) {
    for (int m = 0; m <= n; ++m) {
      EXPECT_EQ(c.g_sv[n][m], 0.0) << "n=" << n << " m=" << m;
      EXPECT_EQ(c.h_sv[n][m], 0.0) << "n=" << n << " m=" << m;
    }
  }
}

TEST(IgrfFile, InsideTheGridEverySecularVariationDegreeIsPopulated) {
  // A derived rate is exact at every tabulated degree, unlike the published SV
  // column, so the snapshot for an in-grid date carries SV all the way up.
  const env::IgrfCoefficients c = loadOrFail(2012.0);
  EXPECT_DOUBLE_EQ(c.epoch_year, 2010.0);
  EXPECT_EQ(c.sv_degree, c.degree);
}

TEST(IgrfFile, RefusesDatesBeforeTheModelBegins) {
  env::IgrfCoefficients c{};
  std::string error;
  EXPECT_FALSE(world::loadIgrfFile(coeffsPath(), 1899.0, c, &error));
  EXPECT_NE(error.find("precedes"), std::string::npos) << error;
}

TEST(IgrfFile, ReportsAMissingFile) {
  env::IgrfCoefficients c{};
  std::string error;
  EXPECT_FALSE(world::loadIgrfFile("/nonexistent/igrf.txt", 2026.0, c, &error));
  EXPECT_NE(error.find("cannot open"), std::string::npos) << error;
}

TEST(IgrfFile, RejectsMalformedInput) {
  struct Case {
    const char* name;
    const char* text;
    const char* expect;
  };

  const Case cases[] = {
      {"igrf_no_header.txt", "g 1 0 -31543 -29350.0 12.6\n", "epoch header"},
      {"igrf_short_row.txt", "g/h n m 2020.0 2025.0 2025-30\ng 1 0 -29404\n", "expected"},
      {"igrf_bad_kind.txt", "g/h n m 2020.0 2025.0 2025-30\nx 1 0 -29404 -29350 12.6\n", "kind"},
      {"igrf_bad_degree.txt", "g/h n m 2020.0 2025.0 2025-30\ng 99 0 -29404 -29350 12.6\n",
       "out of range"},
      {"igrf_empty.txt", "# only a comment\n", "no IGRF coefficients"},
  };
  for (const Case& c : cases) {
    const std::string path = writeTemp(c.name, c.text);
    env::IgrfCoefficients coefficients{};
    std::string error;
    SCOPED_TRACE(c.name);
    EXPECT_FALSE(world::loadIgrfFile(path, 2026.0, coefficients, &error));
    EXPECT_NE(error.find(c.expect), std::string::npos) << error;
    std::remove(path.c_str());
  }
}

TEST(IgrfFile, RejectsANonFiniteEpoch) {
  env::IgrfCoefficients c{};
  std::string error;
  EXPECT_FALSE(world::loadIgrfFile(coeffsPath(), std::nan(""), c, &error));
  EXPECT_NE(error.find("finite"), std::string::npos) << error;
}
