/// @file Unit tests for the NRLMSIS 2.1 truth atmosphere (REQ-SIM-002, §5.2).
///
/// Two kinds of check.
///
/// **Golden.** `MsisGolden.MatchesNrlReferenceOutput` drives every case in
/// upstream's `msis2.1_test_in.txt` through the legacy interface and compares the
/// mass density against upstream's `msis2.1_test_ref_dp.txt`. Both files come from
/// the fetched tarball, never from our tree — so this validates the whole vendored
/// chain (download integrity, module build order, the -DDBLE precision flag)
/// against NRL's own numbers, without committing any MSIS-derived data. That
/// distinction matters: the MSIS license restricts data products generated by the
/// model, and a fixture we generated would carry that restriction into our repo
/// and outlive the model's eventual removal. Upstream's own file does not.
///
/// **Properties.** The wrapper tests pin what NRLMSIS buys over the exponential
/// atmosphere and cannot be faked by a static fit: the diurnal bulge, the
/// solar-activity dependence, and the ECI->ECEF reduction actually being applied.
/// They also pin the fail-safe behaviour, since a half-wired model must report no
/// atmosphere rather than a plausible guess.

#include <gtest/gtest.h>

#include <cmath>
#include <cstdint>
#include <Eigen/Core>
#include <Eigen/Geometry>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "constants/constants.hpp"
#include "math/frames.hpp"
#include "math/quaternion.hpp"
#include "math/typed_vector.hpp"
#include "time/leap_seconds.hpp"
#include "time/timescales.hpp"
#include "time/utc.hpp"
#include "world/atmosphere.hpp"
#include "world/nrlmsis.hpp"

extern "C" void polaris_msis_gtd8d(int iyd, float sec, float alt, float glat, float glong,
                                   float stl, float f107a, float f107, const float* ap,
                                   float* d_out);

namespace world = polaris::sim::world;
namespace pm = polaris::math;
namespace pmf = polaris::math::frames;
namespace pt = polaris::time;
namespace pc = polaris::constants;

namespace {

using Eci = pm::Vec3<pmf::ECI>;
using EcefFromEci = pm::Quat<pmf::ECEF, pmf::ECI>;

constexpr double kA = pc::wgs84::kSemiMajorAxis;

/// Frozen dAT = 37 s — the reproducible-MC table (§3.5), which is exactly what a
/// test wants: no leap steps, so epochs convert identically every run.
pt::LeapSecondTable leapTable() {
  return pt::LeapSecondTable::frozen(37);
}

/// Identity ECI->ECEF: longitude then equals right ascension. Fine for tests that
/// only care that *a* reduction was applied consistently.
world::NrlmsisAtmosphere::EciToEcefFn identityRotation() {
  return [](const pt::Tai&, EcefFromEci& q) {
    q = EcefFromEci::Identity();
    return true;
  };
}

/// Rotation by a fixed angle about +Z — stands in for Earth rotation, letting a
/// test move the subsolar point without moving the spacecraft.
world::NrlmsisAtmosphere::EciToEcefFn rotationAboutZ(double angle_rad) {
  return [angle_rad](const pt::Tai&, EcefFromEci& q) {
    const Eigen::Quaterniond e(Eigen::AngleAxisd(angle_rad, Eigen::Vector3d::UnitZ()));
    q = EcefFromEci(pm::Quaternion(e.w(), e.x(), e.y(), e.z()));
    return true;
  };
}

pt::Tai epochAt(std::int64_t year, unsigned month, unsigned day, unsigned hour,
                const pt::LeapSecondTable& leap) {
  pt::UtcDateTime utc;
  utc.year = year;
  utc.month = month;
  utc.day = day;
  utc.hour = hour;
  return pt::taiFromUtc(utc, leap);
}

/// A ready-to-use model at a representative LEO altitude. Skips the whole test
/// if the coefficient file is unavailable rather than reporting a false failure.
Eigen::Vector3d leoPosition(double altitude_m = 400e3) {
  return Eigen::Vector3d(kA + altitude_m, 0.0, 0.0);
}

}  // namespace

// --- Golden: our build vs NRL's own reference output -------------------------

TEST(MsisGolden, MatchesNrlReferenceOutput) {
  // gtd8d self-initializes from a bare "msis21.parm" in the working directory if
  // nothing has initialized the model yet, which would not find the fetched copy.
  // Constructing the wrapper first loads the coefficient file from its real path.
  const world::NrlmsisAtmosphere init;
  ASSERT_TRUE(init.good()) << init.error();

  const std::string dir = POLARIS_MSIS_SOURCE_DIR;
  std::ifstream in(dir + "/msis2.1_test_in.txt");
  std::ifstream ref(dir + "/msis2.1_test_ref_dp.txt");
  ASSERT_TRUE(in.good()) << "fetched NRLMSIS input not found under " << dir;
  ASSERT_TRUE(ref.good()) << "fetched NRLMSIS reference not found under " << dir;

  std::string header;
  std::getline(in, header);
  std::getline(ref, header);

  int cases = 0;
  std::string in_line;
  std::string ref_line;
  while (std::getline(in, in_line) && std::getline(ref, ref_line)) {
    if (in_line.empty() || ref_line.empty()) {
      break;
    }
    std::istringstream is(in_line);
    int iyd = 0;
    float sec = 0, alt = 0, glat = 0, glong = 0, stl = 0, f107a = 0, f107 = 0, apd = 0;
    ASSERT_TRUE(is >> iyd >> sec >> alt >> glat >> glong >> stl >> f107a >> f107 >> apd)
        << "malformed input line: " << in_line;

    // Upstream's test program sets only ap(1); the rest are left at zero.
    float ap[7] = {apd, 0, 0, 0, 0, 0, 0};
    float d[10] = {};
    polaris_msis_gtd8d(iyd, sec, alt, glat, glong, stl, f107a, f107, ap, d);

    // Reference columns: 9 input fields, then the 10 densities. Mass density is
    // the 6th density (index 5), in g/cm^3.
    std::istringstream rs(ref_line);
    double skip = 0.0;
    for (int i = 0; i < 9; ++i) {
      ASSERT_TRUE(rs >> skip) << "malformed reference line: " << ref_line;
    }
    double expected = 0.0;
    for (int i = 0; i <= 5; ++i) {
      ASSERT_TRUE(rs >> expected) << "malformed reference line: " << ref_line;
    }

    // The reference is printed to 4 significant figures, so that is the tightest
    // agreement the file can express.
    EXPECT_NEAR(static_cast<double>(d[5]), expected, std::abs(expected) * 1e-3)
        << "case " << cases << " (iyd=" << iyd << " alt=" << alt << ")";
    ++cases;
  }

  EXPECT_EQ(cases, 200) << "expected upstream's full 200-case reference set";
}

// --- Wrapper: initialization and fail-safe behaviour -------------------------

TEST(Nrlmsis, LoadsTheFetchedCoefficientFile) {
  const world::NrlmsisAtmosphere msis;
  EXPECT_TRUE(msis.good()) << msis.error();
}

TEST(Nrlmsis, AMissingCoefficientFileDegradesToZeroRatherThanCrashing) {
  // msisinit halts the process on a bad file, so the wrapper must catch this
  // before calling in. If this test ever crashes the suite, that guard is gone.
  const world::NrlmsisAtmosphere msis("/nonexistent/msis21.parm");
  EXPECT_FALSE(msis.good());
  EXPECT_FALSE(msis.error().empty());

  const pt::LeapSecondTable leap = leapTable();
  world::NrlmsisAtmosphere broken("/nonexistent/msis21.parm");
  broken.setEciToEcef(identityRotation());
  broken.setLeapSeconds(&leap);
  EXPECT_EQ(broken.density(epochAt(2020, 6, 1, 12, leap), Eci(leoPosition())), 0.0);
}

TEST(Nrlmsis, RefusesASecondCoefficientSetRatherThanRepointingTheFirst) {
  // The model's coefficients live in Fortran module globals, so loading a second
  // parameter file would silently change the answers for every instance already
  // constructed. Two instances on the SAME file share it; a different file is
  // refused. Without this guard the class API implies an independence the
  // underlying model does not have.
  const world::NrlmsisAtmosphere first;
  ASSERT_TRUE(first.good()) << first.error();

  const world::NrlmsisAtmosphere same;
  EXPECT_TRUE(same.good()) << "same coefficient file should share, not conflict";

  // A readable file that is not the loaded one: any other existing file will do,
  // since the path check happens before MSIS ever reads it.
  const world::NrlmsisAtmosphere other(std::string(POLARIS_MSIS_SOURCE_DIR) + "/readme.txt");
  EXPECT_FALSE(other.good());
  EXPECT_NE(other.error().find("already initialized"), std::string::npos) << other.error();
}

TEST(Nrlmsis, ReportsNoAtmosphereUntilFullyWired) {
  const pt::LeapSecondTable leap = leapTable();
  const pt::Tai epoch = epochAt(2020, 6, 1, 12, leap);
  const Eci r{leoPosition()};

  world::NrlmsisAtmosphere msis;
  ASSERT_TRUE(msis.good()) << msis.error();

  EXPECT_EQ(msis.density(epoch, r), 0.0) << "no resolvers set";

  msis.setEciToEcef(identityRotation());
  EXPECT_EQ(msis.density(epoch, r), 0.0) << "leap seconds still missing";

  msis.setLeapSeconds(&leap);
  EXPECT_GT(msis.density(epoch, r), 0.0) << "fully wired -> real density";
}

TEST(Nrlmsis, ReportsNoAtmosphereBelowTheGround) {
  const pt::LeapSecondTable leap = leapTable();
  world::NrlmsisAtmosphere msis;
  ASSERT_TRUE(msis.good()) << msis.error();
  msis.setEciToEcef(identityRotation());
  msis.setLeapSeconds(&leap);

  const Eigen::Vector3d inside(kA - 10e3, 0.0, 0.0);
  EXPECT_EQ(msis.density(epochAt(2020, 6, 1, 12, leap), Eci(inside)), 0.0);
}

// --- Wrapper: the physics the exponential model cannot represent -------------

TEST(Nrlmsis, DensityFallsOffWithAltitude) {
  const pt::LeapSecondTable leap = leapTable();
  world::NrlmsisAtmosphere msis;
  ASSERT_TRUE(msis.good()) << msis.error();
  msis.setEciToEcef(identityRotation());
  msis.setLeapSeconds(&leap);
  const pt::Tai epoch = epochAt(2020, 6, 1, 12, leap);

  double previous = msis.density(epoch, Eci(leoPosition(200e3)));
  for (double alt : {300e3, 400e3, 500e3, 600e3, 800e3}) {
    const double rho = msis.density(epoch, Eci(leoPosition(alt)));
    EXPECT_GT(rho, 0.0) << "at " << alt;
    EXPECT_LT(rho, previous) << "not decreasing at " << alt;
    previous = rho;
  }
}

TEST(Nrlmsis, LeoDensityIsPhysicallyPlausible) {
  const pt::LeapSecondTable leap = leapTable();
  world::NrlmsisAtmosphere msis;
  ASSERT_TRUE(msis.good()) << msis.error();
  msis.setEciToEcef(identityRotation());
  msis.setLeapSeconds(&leap);

  // 400 km spans roughly 1e-12 to 1e-11 kg/m^3 across the solar cycle.
  const double rho = msis.density(epochAt(2020, 6, 1, 12, leap), Eci(leoPosition()));
  EXPECT_GT(rho, 1e-13);
  EXPECT_LT(rho, 1e-10);
}

TEST(Nrlmsis, HigherSolarActivityRaisesThermosphericDensity) {
  // The single largest effect the exponential atmosphere misses entirely: an
  // order-of-magnitude swing over the solar cycle. If F10.7 does not move the
  // answer, the space-weather inputs are not reaching the model.
  const pt::LeapSecondTable leap = leapTable();
  const pt::Tai epoch = epochAt(2020, 6, 1, 12, leap);
  const Eci r{leoPosition(500e3)};

  world::NrlmsisAtmosphere quiet;
  ASSERT_TRUE(quiet.good()) << quiet.error();
  quiet.setEciToEcef(identityRotation());
  quiet.setLeapSeconds(&leap);
  world::SpaceWeather low;
  low.f107a = 70.0;
  low.f107 = 70.0;
  quiet.setSpaceWeather(low);

  world::NrlmsisAtmosphere active;
  ASSERT_TRUE(active.good()) << active.error();
  active.setEciToEcef(identityRotation());
  active.setLeapSeconds(&leap);
  world::SpaceWeather high;
  high.f107a = 240.0;
  high.f107 = 240.0;
  active.setSpaceWeather(high);

  const double rho_low = quiet.density(epoch, r);
  const double rho_high = active.density(epoch, r);
  EXPECT_GT(rho_low, 0.0);
  EXPECT_GT(rho_high, rho_low * 3.0) << "solar-cycle response is far too weak";
}

TEST(Nrlmsis, TheEciToEcefReductionActuallyChangesTheAnswer) {
  // Longitude sets local solar time, which drives the diurnal bulge. Rotating the
  // frame under a fixed inertial position must therefore move the density. This
  // is the test that fails if the reduction is skipped or stubbed to identity.
  const pt::LeapSecondTable leap = leapTable();
  const pt::Tai epoch = epochAt(2020, 6, 1, 12, leap);
  const Eci r{leoPosition(400e3)};

  double densities[4] = {};
  int i = 0;
  for (double angle : {0.0, 1.5707963, 3.1415927, 4.7123890}) {
    world::NrlmsisAtmosphere msis;
    ASSERT_TRUE(msis.good()) << msis.error();
    msis.setEciToEcef(rotationAboutZ(angle));
    msis.setLeapSeconds(&leap);
    densities[i] = msis.density(epoch, r);
    EXPECT_GT(densities[i], 0.0);
    ++i;
  }

  const double lo = std::min({densities[0], densities[1], densities[2], densities[3]});
  const double hi = std::max({densities[0], densities[1], densities[2], densities[3]});
  EXPECT_GT(hi, lo * 1.05) << "no diurnal variation with longitude";
}

TEST(Nrlmsis, DensityFnAgreesWithTheDirectCall) {
  const pt::LeapSecondTable leap = leapTable();
  world::NrlmsisAtmosphere msis;
  ASSERT_TRUE(msis.good()) << msis.error();
  msis.setEciToEcef(identityRotation());
  msis.setLeapSeconds(&leap);

  const pt::Tai epoch = epochAt(2020, 6, 1, 12, leap);
  const Eci r{leoPosition()};
  const world::DensityFn fn = msis.densityFn();
  EXPECT_DOUBLE_EQ(fn(epoch, r), msis.density(epoch, r));
}

TEST(Nrlmsis, IsDenserThanTheExponentialBaselineAtSolarMaximum) {
  // Not a correctness assertion about either model — a sanity check that the two
  // agree to within an order of magnitude, so the coarse model remains a usable
  // stand-in and a gross unit error in either would show up.
  const pt::LeapSecondTable leap = leapTable();
  world::NrlmsisAtmosphere msis;
  ASSERT_TRUE(msis.good()) << msis.error();
  msis.setEciToEcef(identityRotation());
  msis.setLeapSeconds(&leap);

  const double rho_msis = msis.density(epochAt(2020, 6, 1, 12, leap), Eci(leoPosition()));
  const double rho_exp = world::exponentialDensity(400e3);
  EXPECT_LT(rho_msis, rho_exp * 100.0);
  EXPECT_GT(rho_msis, rho_exp * 0.01);
}
