name: CD

on:
  release:
    types: [published]  # Trigger on published releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt     # If you have a requirements file
          pip install build twine pytest      # Install necessary packages

      - name: Run tests
        run: PYTHONPATH=. pytest tests         # Run the tests in the tests directory

      - name: Build package
        run: python -m build         # Build the package

      - name: Upload to PyPI
        run: |
          pip install twine
          twine upload dist/* -u __token__ -p ${{secrets.PYPI_TOKEN}}
