name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # If you have a requirements file
          #pip install build twine pytest      # Install necessary packages

      - name: Install the package in editable mode
        run: pip install dist/*.whl

      - name: Run tests
       run: pytest tests/

      - name: Build package
        run: python -m build

      #- name: Upload to PyPI
      #  if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only deploy on push to main
      #  run: |
      #    pip install twine
      #    twine upload dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
